### ISSUE TITLE
Version names question

### ISSUE THREAD

**Issue by jaunt** [Typeform/embed#117]
Hello, I have been noticing that most releases seem to require a deliberate npm upgrade.  For example going from 0.30.0 to 0.31.0.   Reading the change logs, it seems like breaking changes aren't very common.  Would it make sense to use the last digit of the version number more often, so that an npm update will upgrade automatically, and reserve the middle digit release for things that require a more conscientious update?

**Comment by prilutskiy** [comment]
@jaunt sorry for the late response - yep, it does make sense. We're working on a new version, and it will follow the flow you've suggested. 👍

**Comment by jaunt** [comment]
Note that it still seems like the major version is changing quite rapidly when it seems like it doesn't need to.  I.e. does 1.5.0 introduce breaking changes?
