### ISSUE TITLE
[BUG] OnSubmit isn't trigger for "conversations" forms. ...typeform.com/c/xxxx

### ISSUE THREAD

**Issue by dmarman** [Typeform/embed#121]
**Describe the bug**
The new "conversations" type of forms doesn't trigger OnSubmit function.

**To Reproduce**
```javascript
// with /c/ url
typeformEmbed.makeWidget(
    element,
    'example.typeform.com/c/xxxx',
    {
        onSubmit: () => {
          console.log('does not work');
        }
    }
);

// with /to/ url
typeformEmbed.makeWidget(
    element,
    'example.typeform.com/to/xxxx',
    {
        onSubmit: () => {
          console.log('works');
        }
    }
);
```

**Expected behavior**
onSubmit should be executed at the end of the conversation form or a new onFinished trigger should be implemented

**Current behavior**
onSubmit is not executed at the end of conversational forms.

**Desktop (please complete the following information):**

- OS: MacOs
- Browser: Chrome
- Embed SDK Version: pulled from https://embed.typeform.com/embed.js

**Comment by mathio** [comment]
Conversations embedding is currently supported by a different library that is not open source. This library does not support conversations embed.

FYI @prilutskiy

**Comment by prilutskiy** [comment]
@dmarman thanks for raising this! Yeah, as @mathio said this isn't yet supported. We plan to revisit this in Q2 2021.

**Comment by dmarman** [comment]
Thanks for the answer :)

This non-open source library for conversations is publicly available for usage like embed.js? I guess not, but just to confirm.

**Comment by mathio** [comment]
@dmarman go to "Share" tab of your typeform, click "Start a conversation", you can copy the code to embed the lib. But it is not published in npm like this lib is.
