### ISSUE TITLE
In Mobile view, closing a typeform after submitting takes us back to the first page in new version.

### ISSUE THREAD

**Issue by vaibhavsah** [Typeform/embed#127]
**In Mobile view, closing a typeform after submitting takes us back to the first page in new version.**
I want to open a typeform as a widget in my page. But in mobile view, the typeform widget shows the welcome screen which is not required for me. Now on clicking the start, the typeform opens in a new fullscreen popup. This was not the behaviour earlier. Now what happens is that on submitting the typeform, the popup remains open. If I close it, it presents me back to the first question of typeform, this time not in a popup. 

**Expected behavior**
Post submission, the typeform in the widget should also show submission screen. And the popup should close by itself. 
**Current behavior**
Post submission, we are presented with the submission screen in the popup. On closing the popup, we are redirected to the first page of typeform in widget mode.

**Screenshots (Please find images below in the order of flow)**
<img width="372" alt="Screenshot 2021-01-12 at 6 07 10 PM" src="https://user-images.githubusercontent.com/12396290/104315845-977fde80-5501-11eb-9cee-4717cf8ffdff.png">
<img width="400" alt="Screenshot 2021-01-12 at 6 08 15 PM" src="https://user-images.githubusercontent.com/12396290/104315873-9fd81980-5501-11eb-8885-234b69e33589.png">
<img width="390" alt="Screenshot 2021-01-12 at 6 08 57 PM" src="https://user-images.githubusercontent.com/12396290/104315888-a36ba080-5501-11eb-9a82-2779670a608c.png">
<img width="387" alt="Screenshot 2021-01-12 at 6 09 20 PM" src="https://user-images.githubusercontent.com/12396290/104315893-a5cdfa80-5501-11eb-88f7-217a10c02914.png">

**Comment by vaibhavsah** [comment]
Please find below the videos of the issues I am getting. 
1. Even if I am on question 3 in popup, on closing in between, the widget mode takes me back to question 1. 
https://user-images.githubusercontent.com/12396290/104317893-9f8d4d80-5504-11eb-8f8a-b37000c46bcf.mp4

2. Even though I have submitted the typeform in popup, on closing the typeform from submission screen, I am taken back to the first question in the widget. 
https://user-images.githubusercontent.com/12396290/104317908-a4ea9800-5504-11eb-8290-eee2ed00f77a.mp4

**Comment by mathio** [comment]
I confirm, I was able to replicate the issue here: https://embed-typeform.glitch.me/

We will look into this.

**Comment by vaibhavsah** [comment]
Thanks @mathio . Please keep us updated here.

**Comment by mathio** [comment]
This is fixed in #133 and has been released as v0.34.1

I tested on https://embed-typeform.glitch.me/

**Comment by vaibhavsah** [comment]
@mathio 
Thanks for the updates. But I can see that for the points mentioned above, 

1. In case of closing the typeform in between, it takes me to start / welcome screen. Instead it should take me to the same question.
2. In case of completion of typeform, on closing, it again takes me to start instead of thank you screen. 
Please check.

**Comment by mathio** [comment]
When you open the popup, we always reopen the typeform from the beginning. If I am not mistaken the behavior has always been like this.

I am tagging this as an enhancement and will let you know when this get on our roadmap.

**Comment by vaibhavsah** [comment]
@mathio When can we expect the enhancements. What are your release timelines ?

**Comment by prilutskiy** [comment]
Add to the team's backlog. We'll take a look at this enhancement in Q2.
