### ISSUE TITLE
[BUG] Refused to frame error with Nextjs/react

### ISSUE THREAD

**Issue by Ciccio99** [Typeform/embed#132]
**Describe the bug**
I've create a react hook that return the open/close functions to any component that needs to utilize it. Whenever the typeform popup window opens the refused to frame error occurs:
`[Report Only] Refused to frame 'https://<domain>.typeform.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors https:".`

**The typeform still functions as usual, even with this error popping up. I'm able to fully complete and submit it.**

**To Reproduce**
This is the hook:
```
import { useState, useEffect } from 'react';
import ROUTES from 'lib/constants/routes';

export default function useTypeform(): {
  closeTypeform: () => void;
  openTypeform: () => void;
} {
  const [typeform, setTypeform] = useState(null);

  useEffect(() => {
    (async () => {
      const { makePopup } = await import('@typeform/embed');

      const reference = makePopup(ROUTES.requestAccess, {
        mode: 'popup',
        autoClose: 1000,
        hideHeaders: true,
        hideFooters: true,
      });

      setTypeform(reference);
    })();
  }, []);

  const closeTypeform = () => {
    if (typeof window !== 'undefined' && typeform !== null) {
      typeform.close();
    }
  };

  const openTypeform = () => {
    if (typeof window !== 'undefined' && typeform !== null) {
      typeform.open();
    }
  };

  return { closeTypeform, openTypeform };
}
```
**Expected behavior**
No errors on opening typeform popup.

**Current behavior**
`[Report Only] Refused to frame 'https://<domain>.typeform.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors https:"` - Error appears

**Desktop:**
- Browser - Chrome[Version 88.0.4324.96] - Nextjs **Local development**
- Browser - Safari[Version 14.0.2 ] - Nextjs **Live Deployment**

**Comment by mathio** [comment]
I tried using your code and I am unable to replicate this issue: 
https://codesandbox.io/s/react-embed-hook-mptcc?file=/src/App.js

You most likely need to [update your CSP headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP).

**Comment by Ciccio99** [comment]
This may be a problem with NextJS and CSP then. I appreciate the feedback - will close the issue in the meantimetime.

**Comment by joernroeder** [comment]
works for me as well.
