### ISSUE TITLE
[BUG] regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by timhagn** [Typeform/embed#161]
**Describe the bug**
After updating `@typeform/embed` in a Gatsby project from `v0.33.2` to `v0.34.5` and either running develop or production mode the following error is thrown:

```sh
  WebpackError: ReferenceError: regeneratorRuntime is not defined
  
  - lib.pure.js:1 
    node_modules/@typeform/embed/build/lib.pure.js:1:41435
```

**To Reproduce**

Install `@typeform/embed` @ `v0.34.5`in a Gatsby project, add it as described & run `yarn build` (or `yarn develop` then it's shown in the Browser).
(But probably with many a React App).

**Expected behavior**
Typeform doesn't throw an error ; ).

**Desktop (please complete the following information):**
```
  System:
    OS: Linux 5.4 Linux Mint 20.1 (Ulyssa)
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.15.3 - ~/.nvm/versions/node/v14.15.3/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 7.5.2 - ~/.nvm/versions/node/v14.15.3/bin/npm
  Browsers:
    Chrome: 87.0.4280.88
    Firefox: 85.0
  npmPackages:
    gatsby: ^2.32.3 => 2.32.3
```

**Additional context**
 I know you state in the README that no polyfills are included, but you might perhaps add that
`@babel/plugin-transform-runtime` is needed. But as it quite increases the bundle size, I refrain from it and stay @ `v0.33.2`.

**Comment by daviddelusenet** [comment]
Please fix this bug 🙏

**Comment by daviddelusenet** [comment]
@timhagn for me it used to work the first time I installed it today. However, once I removed my `node_modules` and reinstalled my dependencies I started experiencing this error.

When I downgrade to `0.33.2` I get an ` WebpackError: ReferenceError: window is not defined` error.

This is my implementation:

```tsx
import React, {
  createContext,
  ReactNode,
  FunctionComponent,
  useMemo,
  useCallback,
} from 'react'
import * as typeformEmbed from '@typeform/embed'

export interface EarlyAccessFormContext {
  openForm: () => void
}

export const earlyAccessFormContext = createContext<EarlyAccessFormContext>({
  openForm: () => undefined,
})

interface EarlyAccessFormProviderProps {
  children: ReactNode
}

const EarlyAccessFormProvider: FunctionComponent<EarlyAccessFormProviderProps> = ({
  children,
}) => {
  const form = useMemo(
    () =>
      typeformEmbed.makePopup(
        'MY_URL',
        {
          size: 90,
        },
      ),
    [],
  )

  const openForm = useCallback(() => {
    form.open()
  }, [form])

  return (
    <earlyAccessFormContext.Provider
      value={{
        openForm,
      }}
    >
      {children}
    </earlyAccessFormContext.Provider>
  )
}

export default EarlyAccessFormProvider

export const EarlyAccessFormConsumer = earlyAccessFormContext.Consumer
```

Any idea??

**Comment by daviddelusenet** [comment]
It seems to be related to this part:

```tsx
  const form = useMemo(
    () =>
      typeformEmbed.makePopup(
        'MY_URL',
        {
          size: 90,
        },
      ),
    [],
  )
```

When I remove that it my code compiles fine. Even if I wrap this code in a if statement like `if (typeof window !== 'undefined')` I'm still getting this error.

**Comment by timhagn** [comment]
Hi @daviddelusenet,

strange, this Problem I don't get during build. Are you also working with Gatsby?
For other libs with a `window` error I have had good experience with [loadable-components](https://loadable-components.com/docs/library-splitting/) encapsulating them, though I don't know if it might be of help here % ).
No one reading this from @Typeform?

Best,

Tim.

**Comment by daviddelusenet** [comment]
Yeah it has to do with the combination of `useMemo` together with this library. If out outcomment my `useMemo`, start my project and then uncomment my code again the popup works fine.

However, if I then restart my project with the code still uncommented I get the error mentioned above. I'll investigate an approach without using `useMemo`.

**Comment by daviddelusenet** [comment]
This also doesn't work 😩 

```tsx
const formRef = useRef<typeformEmbed.Popup | null>(null)

useEffect(() => {
  if (typeof window !== 'undefined' && window) {
    formRef.current = typeformEmbed.makePopup(
      'MY_FORM_URL,
      {
        size: 90,
      },
    )
  }
}, [])
```

**Comment by daviddelusenet** [comment]
So I managed to fix it by using the approach of Ciccio99 in issue #132. My code for if anyone ever gets here:

```tsx
import { useCallback, useEffect, useRef } from 'react'
import { Popup } from '@typeform/embed'

export const useEarlyAccessForm = (): {
  openForm: () => void
} => {
  const formRef = useRef<Popup | null>(null)

  useEffect(() => {
    ;(async () => {
      const { makePopup } = await import('@typeform/embed')

      formRef.current = makePopup(
        'MY_FORM_URL,
        {
          size: 90,
        },
      )
    })()
  }, [])

  const openForm = useCallback(() => {
    formRef.current?.open()
  }, [formRef])

  return {
    openForm,
  }
}

```

**Comment by lpke** [comment]
> So I managed to fix it by using the approach of Ciccio99 in issue #132. My code for if anyone ever gets here:
> 
> ```tsx
> import { useCallback, useEffect, useRef } from 'react'
> import { Popup } from '@typeform/embed'
> 
> export const useEarlyAccessForm = (): {
>   openForm: () => void
> } => {
>   const formRef = useRef<Popup | null>(null)
> 
>   useEffect(() => {
>     ;(async () => {
>       const { makePopup } = await import('@typeform/embed')
> 
>       formRef.current = makePopup(
>         'MY_FORM_URL,
>         {
>           size: 90,
>         },
>       )
>     })()
>   }, [])
> 
>   const openForm = useCallback(() => {
>     formRef.current?.open()
>   }, [formRef])
> 
>   return {
>     openForm,
>   }
> }
> ```

I've been trying to solve this issue as well and your code helped me find a solution that worked, thank you! For me it was dynamically importing the module that did the trick. However as I'm embedding directly, I had some issues with the ref not being found before I call `makeWidget()`. I solved this with a callback ref, which is checked inside `useEffect`. I'll post my entire `<Typeform>` component below:

```tsx
import React, { useState } from "react";
import { useEffect } from "react";
import { WidgetOptions } from "typeform__embed";
import CenterSpinner from "components/CenterSpinner";
import { Box } from "@material-ui/core";

type TypeformProps = {
  id: string;
  onLoaded?: () => void;
  options?: Omit<WidgetOptions, "onReady">;
};

/**
 * Simple implementation of the Typeform Embed script (npm: @typeform/embed).
 *
 * Returns a div that will size itself to fill parent element and display a
 * Typeform of specified form `id`. Displays spinner while loading.
 *
 * Optionally accepts an 'options' prop object that will be passed to the
 * `makeWidget()` call:
 *
 * ------
 *
 * - `onLoaded?: () => void` - used in place of default `onReady`
 * - `opacity?: number`
 * - `buttonText?: string`
 * - `hideScrollbars?: boolean`
 * - `hideFooter?: boolean`
 * - `hideHeaders?: boolean`
 * - `onSubmit?: (event: OnSubmitEvent) => void`
 * - `disableTracking?: boolean`
 *
 * ---
 *
 * [Package Docs on npm](https://www.npmjs.com/package/@typeform/embed)
 * */
const Typeform: React.FC<TypeformProps> = ({
  id = "",
  onLoaded = () => undefined,
  options = {},
}) => {
  const [typeformRef, setTypeformRef] = useState<HTMLDivElement | null>(null);
  const [formLoaded, setFormLoaded] = useState(false);

  function handleOnLoaded() {
    setFormLoaded(true);
    onLoaded();
  }

  useEffect(() => {
    if (typeformRef) {
      (async () => {
        const { makeWidget } = await import("@typeform/embed");

        makeWidget(
          typeformRef,
          `https://form.typeform.com/to/${id}`,
          {
            onReady: () => handleOnLoaded(),
            ...options,
          }
        );
      })();
    }
  }, [typeformRef]);

  return (
    <Box height="100%" width="100%">
      {!formLoaded && <CenterSpinner />}
      <div
        style={{
          height: "100%",
          width: "100%",
          display: formLoaded ? "block" : "none",
        }}
        ref={setTypeformRef}
      />
    </Box>
  );
};

export default Typeform;

```

Note: The `Box` component can be substituted for any container, and the `<CenterSpinner>` is a loading spinner that is replaced with the embedded form once it loads.

**Comment by daviddelusenet** [comment]
Nice @lpke ! However, couldn't you just do this?

```tsx
  const typeformRef = useRef(null);
  const [formLoaded, setFormLoaded] = useState(false);

  function handleOnLoaded() {
    setFormLoaded(true);
    onLoaded();
  }

  useEffect(() => {
    if (typeformRef.current) {
      (async () => {
        const { makeWidget } = await import("@typeform/embed");

        makeWidget(
          typeformRef,
          `https://form.typeform.com/to/${id}`,
          {
            onReady: () => handleOnLoaded(),
            ...options,
          }
        );
      })();
    }
  }, [typeformRef]);
```

I also decided to rewrite my code a bit to make it more readable, it still works the same:

```tsx
const formRef = useRef<Popup | null>(null)

useEffect(() => {
  const renderForm = async () => {
    const { makePopup } = await import('@typeform/embed')

    formRef.current = makePopup(
      // @TODO where should this URL be stored?
      'https://ledo-preregistration.typeform.com/to/BTqQJRyM',
      {
        size: 90,
      },
    )
  }

  renderForm()
}, [])
```

So in your case you could just check for `formRef.current` inside the `renderForm` function and then create your widget:

```tsx
const formRef = useRef<Popup | null>(null)

useEffect(() => {
  const renderForm = async () => {
    if (formRef.current) {
        const { makeWidget } = await import("@typeform/embed");

        makeWidget(
          typeformRef.current,
          `https://form.typeform.com/to/${id}`,
          {
            onReady: () => handleOnLoaded(),
            ...options,
          }
        );
     }
  }
  
  renderForm()
}, [formRef])

```

**Comment by lpke** [comment]
@daviddelusenet I did try that initially, but for some reason I kept getting "typeformRef is not a valid DOM Element" - or something like that. I definitely tried both with and without `.current`, didn't seem to make a difference strangely. I'm sure I missed something though. I'll give your code a shot when I'm on my development machine next and get back to you.
