### ISSUE TITLE
[BUG]: can't use embed SDK with angular

### ISSUE THREAD

**Issue by AdrienVictor** [Typeform/embed#177]
How can we use the sdk with angular?
When following the guide I end with the following errors:

Error: ./node_modules/@typeform/embed/build/lib.pure.js
Module not found: Error: Can't resolve 'react' in '/Users/freer/Desktop/Slush/node2.0/node-by-slush/node_modules/@typeform/embed/build'

Error: ./node_modules/@typeform/embed/build/lib.pure.js
Module not found: Error: Can't resolve 'react-dom' in '/Users/freer/Desktop/Slush/node2.0/node-by-slush/node_modules/@typeform/embed/build'

Is there a fix on embedding typeform popup on an angular project? 
Happy to hear suggestions :) 

**To Reproduce**
On angular 11
npm install --save @typeform/embed

in my typescript file:

`openInvestorTypeForm() {
    const reference = typeformEmbed.makePopup(
      'https://developerplatform.typeform.com/to/Xc7NMh', 
      {
        mode: 'popup',
        autoClose: 3000,
        hideHeaders: true,
        hideFooters: true,
        onSubmit: function () {
          console.log('Typeform successfully submitted');
        },
      }
    );

    reference.open();

    setTimeout(function () {
      reference.close();
    }, 10000); 
  }`

**Expected behavior**
I should get the embedded typform as a popup like specified in the sdk guide.

Please let me know if you successfully managed to embed a typeform on angular using the sdk, or anything else for that matter!

Thanks a lot in advance!

**Comment by mathio** [comment]
Yes, our embed lib at the moment requires `react` and `react-dom` as peer dependencies. You will need to install those as well:

```
yarn add react react-dom
```

Here is an example Angular app with typeform popup embed, works just fine:
https://codesandbox.io/s/angular-embed-fnf7w

We understand it is not ideal to install react when you are not using it in your app. We are currently developing new version of this lib that will not require react dependency. I will keep you updated.

In the mean time please to close this issue if this resolved your issue.

**Comment by AdrienVictor** [comment]
Thanks a lot for the help!
I'll test this out and see how it works.

Do you have an idea when the new version will be released? just a rough estimate ☺️?

Thanks again!

**Comment by mathio** [comment]
Hopefully by the end of March.

**Comment by AdrienVictor** [comment]
Thanks for letting me know!

Is there any option to follow up on the advancement of the release? 😀

**Comment by mathio** [comment]
Not yet. We will keep you posted.

**Comment by mathio** [comment]
The new version is out now.

**Comment by AdrienVictor** [comment]
Thanks a lot!

Just to make sure, the new version is this one right: "[Vanilla JavaScript Embed Library](https://github.com/Typeform/embed/tree/main/packages/embed) if you are not using React"

So only vanilla JS version?

**Comment by mathio** [comment]
@AdrienVictor thats correct!
