### ISSUE TITLE
[BUG]makePopup is not a function when trying to implement typeform popover inReact/Gatsby

### ISSUE THREAD

**Issue by tunztunztunz** [Typeform/embed#190]
**Describe the bug**
I've been trying to follow the guide to embedding a typeform widget in a React component, but I'm receiving a webpack error. I tried to use makePopup too, but also recieved the error.
I'm using this code 
```
import React, { useEffect, useRef, useState } from "react";
import * as typeformEmbed from "@typeform/embed";

export const Quiz = () => {
  const typeformRef = useRef(null);
  const url =
    "https://form.typeform.com/to/P9O5wcaX?typeform-medium=embed-snippet";
  useEffect(() => {
    typeformEmbed.makeWidget(
      typeformRef.current,
      "https://form.typeform.com/to/MY_TYPEFORM_ID",
      {
        hideFooter: true,
        hideHeaders: true,
        opacity: 50
      }
    );
  }, [typeformRef]);
  console.log(typeformRef);

  return (
    <div ref={typeformRef} style={{ height: "100vh", width: "100%" }}></div>
  );
};
```
and receiving this error
```Uncaught TypeError: _typeform_embed__WEBPACK_IMPORTED_MODULE_1__.makeWidget is not a function```

**Comment by lucashu1** [comment]
Getting a similar error with Next.js. My guess is that it has something to do with server-side rendering, but I'm not entirely sure. Any pointers would be appreciated!

```
TypeError: _typeform_embed__WEBPACK_IMPORTED_MODULE_7__["makeWidget"] is not a function. (In '_typeform_embed__WEBPACK_IMPORTED_MODULE_7__["makeWidget"](elm, url, options)', '_typeform_embed__WEBPACK_IMPORTED_MODULE_7__["makeWidget"]' is undefined)
```

**Comment by HairMachine** [comment]
I also see this in Vue. There is a createWidget function in there though! I'm not sure if it's the same thing or not; I get an InnerHTML error when I pass the element into that (this could still be user error on my part).

**Comment by tunztunztunz** [comment]
@lucashu1 @HairMachine 

I was able to get this to work in React/Gatsby by running this code on the layout index.tsx: 

```
  useEffect(() => {
    let mounted = true;
    if (mounted) {
      const initializeScripts = () => {
        loadScript("https://embed.typeform.com/embed.js", () => {
          () => {};
        });
      };
      initializeScripts();
    }
    return () => {
      mounted = false;
    };
  }, []);
```

Here's loadScript() 
```
export const loadScript = (url: string, cb: GlobalEventHandlers["onload"]) => {
  const element = document.getElementsByTagName("script")[0];
  const fjs = element;
  const js = document.createElement("script");
  js.id = "widget-script";
  js.src = url;
  if (fjs && fjs.parentNode) {
    fjs.parentNode.insertBefore(js, fjs);
  } else {
    document.head.appendChild(js);
  }
  js.onload = cb;
};
```

And then I have my component with the link tag and SVG below this at the bottom of my layout index.tsx. I had to use this solution for another 3rd party script that wasn't working in React and figured this was the way. I'm not using this package at all. Hopefully, this will help anyone else having this issue.

**Comment by psabbagh** [comment]
I'm having the same issue in Gatsby on makePopup. The function is in there but for some reason it is giving below error:

`undefined is not a function (near '..._typeform_embed__WEBPACK_IMPORTED_MODULE_2__.makePopup...')`

**Comment by FullStackTiger** [comment]
I am getting this error on gatsby project too.
TypeError: _typeform_embed__WEBPACK_IMPORTED_MODULE_5__.makeWidget is not a function

**Comment by rrosztoczy** [comment]
I got the same error trying to use makeWidget in my nextjs app. On inspection, I only have access to "createWidget" which I am using and it works.

**Comment by psabbagh** [comment]
Updating to v 1.0.0-next.16 fixed the makePopup error. Getting another `Failed to load resource` error.

**Comment by wamujlb** [comment]
Have tried to use and it didn't work. I use simple react app without SSR. Does anyone know how this can be used in React?

**Comment by flppv** [comment]
Had the same issue with React app. Had to revert the package version to a stable one: `yarn add @typeform/embed@0.34.6`. It helped.

**Comment by wamujlb** [comment]
@flppv decided to write my own small wrapper.

**Comment by mathio** [comment]
Latest released version (>= 1) now works with server-side rendering. You can see [a demo implementation in Next.js here](https://github.com/Typeform/embed/tree/main/packages/demo-nextjs).
