### ISSUE TITLE
[BUG] 'Cannot set property 'innerHTML' of undefined' on createWidget if React ref.current is used as element (since release v1.0 !)

### ISSUE THREAD

**Issue by arnoutj** [Typeform/embed#197]
**Describe the bug**

The v1.0 version of this package gives an undefined error on createWidget(element, ....) if passed a ref.current value in React.

This worked fine in version 0.34.6. Also, makeWidget is now createWidget apparently, so I think the docs are lagging behind.

**To Reproduce**

1. Install @typeform/embed (latest)
2. Add the following code:

```
import React, { useRef, useEffect } from 'react'
import * as typeformEmbed from '@typeform/embed'

const MyTypeform = () => {
  const typeformRef = useRef(null)

  useEffect(() => {
    typeformEmbed.makeWidget(typeformRef.current, 'https://form.typeform.com/to/MY_TYPEFORM_ID', {
      hideFooter: true,
      hideHeaders: true,
      opacity: 50,
    })
  }, [typeformRef])

  return <div ref={typeformRef} style={{ height: '100vh', width: '100%' }}></div>
}
```

**Expected behavior**
I expect the form embed to load as usual.

**Current behavior**
The ref.current value seems to be handled incorrectly when the createWidget method is called.

Problem 1: makeWidget does not exist anymore, please update the docs.

![Typeform error](https://user-images.githubusercontent.com/1426169/109973192-626d5c80-7cf8-11eb-892f-8e50fc77037a.png)

Problem 2: 'Cannot set property 'innerHTML' of undefined

![Typeform error 2](https://user-images.githubusercontent.com/1426169/109973425-a95b5200-7cf8-11eb-9c26-05c6e1d8ec30.png)

**Comment by wisejayden** [comment]
This is still an issue

**Comment by luisccode** [comment]
I have the same issue.  Version 0.34.6 works correctly

**Comment by viperfx** [comment]
Also facing the same issues, tried multiple versions.

Does anyone at Typeform work on this library? I am so shocked that such a large company created an SDK that has such a critical issue like this.

**Comment by saygun** [comment]
The latest release version on npm is `1.0.0-next.16`. I am also facing the same issue. I checked the installed source code and found this:
```typescript
export const createWidget = (formId: string, options: WidgetOptions): Widget => {
  if (!hasDom()) {
    return {
      refresh: () => {},
    }
  }

  const iframe = createIframe(formId, 'widget', options)
  const widget = buildWidget(iframe)

  options.container.innerHTML = ''
  options.container.append(widget)

  return {
    refresh: () => iframe.contentWindow?.location.reload(),
  }
}
```

This function is working for me now. You can find what the `WidgetOptions` are in `node_modules/@typeform/embed/src/factories/create-widge/widget-options.ts`

**Comment by Sandstedt** [comment]
@arnoutj 
It works fine if you don't look at the outdated documentation on their site, instead using this example that is linked in this repos README.md:

https://github.com/Typeform/embed/tree/main/packages/demo-react

So it's not a bug, it's just old documentation for an API that has changed.

**Comment by mathio** [comment]
Sorry about the delay on releasing the documentation. it is now up to date for version >= 1 on both Github and [our developers portal](https://developers.typeform.com/embed/).

You can also find the latest examples in [demo packages in the repo](https://github.com/Typeform/embed/blob/main/packages/), there is also [an example for React](https://github.com/Typeform/embed/blob/main/packages/demo-react/src/App.js).
