### ISSUE TITLE
Retrieve id of current page

### ISSUE THREAD

**Issue by HerrNiklasRaab** [Typeform/embed#199]
**Is your feature request related to a problem? Please describe.**
Because there is the callback `onScreenChanged` I would like to use this to customize tracking. Currently, Typeform only supports tracking with Google Analytics. But not we are running Google Adwords ads. You can track conversions for Google Adwords using Google Analytics, but there are some differences between Google Adwords conversion tracking and Google Analytics Conversion tracking. Those are explained here: https://www.optimizesmart.com/difference-between-google-adwords-and-google-analytics-conversion-tracking

**Describe the solution you'd like**
Ideal for me would be if the `onScreenChanged` callback would have a parameter, that enables me to identify which page is currently shown to the user. I could then pass the name of the page (question) to the tracking API.

**Describe alternatives you've considered**
Google Analytics

**Comment by mathio** [comment]
Sorry for the delay. I have added this to our backlog. We can send question ID (or ref) as payload to `onQuestionChanged`. I will let you know once this is released.

**Comment by mathio** [comment]
Hello, we have recently implemented necessary changes to pass question `ref` to `onScreenChanged`. And we just released [version 1.2.0 to npm](https://www.npmjs.com/package/@typeform/embed) to support this feature. For details [see related section of README file](https://github.com/Typeform/embed/tree/main/packages/embed#callbacks).
