### ISSUE TITLE
Get Responses after Submit

### ISSUE THREAD

**Issue by DanielWahl** [Typeform/embed#209]
Hey folks,

How can I get the responses/answers after submitting a form? (onSubmit)

I need to get the response from one form, to create a new widget with a new form.
F.e.:
- 1st Form: Select Gender
- 2nd Form: Show Questions from either male- or female-form

Thanks in advance for your help.

**Comment by prilutskiy** [comment]
Hi @DanielWahl, that a great question!
`onSubmit` receives `responseId` in parameters, so you could use [Typeform Responses API](https://developer.typeform.com/responses/) to retrieve the answers from the platform. Please try that approach and let us know if you face any issues 😉

**Comment by DanielWahl** [comment]
I also tried with Typeform/JS-Api-Client, but it's not working because of the updated Cors policy (in my case) [](https://github.com/Typeform/js-api-client/issues/55)

Is it possible to retrieve the Responses with the Responses API without login and asking for a bearer-token every time? (f.e. via client_id, ...)
I'm using the Typeform Embed inside a Wordpress Theme, so it wouldn't be ideal to create a separate API to get the responses to evaluate.

**Comment by prilutskiy** [comment]
@DanielWahl, I'd personally go with the API Token approach. You can obtain one by going to your account settings > personal tokens. More info here: https://developer.typeform.com/get-started/personal-access-token/

**Comment by DanielWahl** [comment]
I tried the Response API with the Personal Token.
Everything is working fine on localhost with Cors enabled (via Browser Plugin)

But on production, I only get a `blocked by CORS policy: No 'Access-Control-Allow-Origin' header`- error.

Is there any possibility to add a Uri to the Typeform API, so the Requests does not get blocked?

The request is done via fetch on client side.

```
createWidget("xxxxxxxx", {
	container: this.container,
        onSubmit: (event) => {
              let id = event.responseId
              let url = new URL("https://api.typeform.com/forms/xxxxxxxx/responses")
              let params = {included_response_ids: id}
              url.searchParams.append("included_response_ids", id)
              const call = async () => {
                    await fetch(url, {
		        method: 'GET',
		        mode: 'cors',
		        headers: {
	                      "Authorization": `Bearer ${process.env.ACCESS_TOKEN}`,
		        },
	            })
                    .then(response => response.json())
                    .then((res) => {
		         console.table(res);
                    })
              }
        }
}
```

**Comment by BrunoAderaldo** [comment]
Hello @DanielWahl, did you manage to fix that? I have the same issue, using pretty much the same solution, but I always get this error about CORS.
