### ISSUE TITLE
Size, Width & Height options are not implemented

### ISSUE THREAD

**Issue by ch1ll0ut1** [Typeform/embed#217]
As the title states, none of this three arguments are currently working. 
The source code shows thats its simple missing to assign the option to the iframe dom object:
https://github.com/Typeform/embed/blob/69c8d48262a32b177590ac2b375780f38abb0660/packages/embed/src/utils/create-iframe/create-iframe.ts#L8

**Comment by mathio** [comment]
It works, for example for popup you can specify `data-tf-size="80"` or `data-tf-width="600" data-tf-height="400"`, see:
https://tf-embed-next-popup-sizes.glitch.me/

For widget the form automatically takes space of the parent element. You can set the size of parent div to control it.

**Comment by ch1ll0ut1** [comment]
@mathio Sorry i wasn't explicit enough. The iframe used for the widget requires width/height settings or atleast the default of 100% for width and height. Currently the widget is not usable because it can not match its parent width & height. You can see the code here: https://codesandbox.io/s/hungry-brown-g173f?file=/index.html

The parent has full width of the window, typeform-embed simply has no options or definition. Since the only width&height options are only used by the popup but not by the widget.

**Comment by rikkert** [comment]
I have the same issue, when creating the widget with JavaScript the size is really small.
Is there a solution to this?
