### ISSUE TITLE
New "takes N+ min" seems to mess up with the layout of the start bar.

### ISSUE THREAD

**Issue by jaunt** [Typeform/embed#234]
![startbtn](https://user-images.githubusercontent.com/5732995/117210540-a8a07400-adac-11eb-9130-c082e78266f0.png)

There's almost no white space below the start button.  Looks very squished.

**Comment by jaunt** [comment]
Also, we tell people it will take 10 minutes.  No idea where 7+ minutes is coming from.

**Comment by mathio** [comment]
If the form does not fit into embed you can increase the height.

If you dont like the "Time to complete" feature, you can [turn it off when you are building your form](https://help.typeform.com/hc/en-us/articles/360052533131-What-is-Time-to-complete-).

**Comment by jaunt** [comment]
@mathio Thanks!  Though it doesn't seem to matter what height I make it.  When I make the view narrow, it makes the grey bar at the bottom, and puts almost no space below the start button.

**Comment by mathio** [comment]
Can you share a page with the embedded typeform? I will have a look tomorrow.

**Comment by jaunt** [comment]
@mathio In order to take our survey you need to create a free account.  If you're willing to do that, singdaptive.com is where you do it from.  No worries if not!

P.s. is that option to turn off time to complete in the new builder perhaps?  We're still using the classic builder and I can't seem to find reference to it.

**Comment by mathio** [comment]
I can see the issue now. I have raised this with our designer.

Yes, you can turn it off in old builder too. You will find the setting under "Question settings" (wrench icon next to welcome screen).

Or if you want access to new builder you can [permanently bring your form to new builder](https://help.typeform.com/hc/en-us/articles/360055204932-New-or-Classic-builder-Which-am-I-using-).

**Comment by mathio** [comment]
This has been fixed recently.
