### ISSUE TITLE
Large bundle size

### ISSUE THREAD

**Issue by bogdansoare** [Typeform/embed#24]
This library comes at a whopping 113.1kB minified https://bundlephobia.com/result?p=@typeform/embed@0.16.0 

That is not very good for just showing a form on a website.

**Comment by bogdansoare** [comment]
```
info Direct dependencies
└─ @typeform/embed@0.16.0
info All dependencies
├─ @emotion/stylis@0.7.1
├─ @emotion/unitless@0.6.7
├─ @typeform/embed@0.16.0
├─ classnames@2.2.6
├─ create-emotion-styled@9.2.8
├─ create-emotion@9.2.12
├─ custom-event@1.0.1
├─ immutability-helper@2.9.1
├─ preact-compat@3.19.0
├─ preact-context@1.1.4
├─ preact-render-to-string@3.8.2
├─ preact-transition-group@1.1.1
├─ preact@8.5.3
├─ scrollbar-width@3.1.1
├─ spin.js@2.3.2
├─ standalone-react-addons-pure-render-mixin@0.1.1
├─ stylis-rule-sheet@0.0.10
└─ stylis@3.5.4
```

That's a lot of dependencies.
My advice, drop css-in-js, just use css. Css-in-jss is not well suited for libraries unless both the library and the app consuming the library use the same css-in-js solution.

Second, have 2 versions of the lib, a vanilla one without preact and a react one that's a wrapper on top of the vanilla one, since react it's the most popular library.

**Comment by Gotusso** [comment]
Hey @bogdansoare thanks for reaching out! Long story short, you're absolutely right, the bundle is too big for what the library does today. This also loads another bundle once the Typeform shows up that it's bigger, and it's impacting user experience the most, so we're focusing on that one first. After that, we will also check how we can shave some size here. 

In the meantime, I'm going to leave the issue open to keep collecting feedback, and as a channel for the improvements we do related to this issue.

**Comment by bogdansoare** [comment]
Hey @Gotusso thank you for the response, glad to hear that you're working on it.
I really like typeform and would be happy if both developers and users will have a nice experience using this library.

All the best.

**Comment by prilutskiy** [comment]
As of now, we reduced the bundle size by 27%. In the nearest future, we'll also be optimizing a bunch of other stuff, so the bundle will become even tinier.

**Comment by jellevandevelde** [comment]
I'm struggling with the same issue here. The bundle size as of date is still very large.
https://bundlephobia.com/result?p=@typeform/embed@0.25.1

I wanted to embed a TypeForm in a Vue app, but seems that I now need to ship my app with both Vue and React in order for me to achieve this.

Any tips in the meantime?

**Comment by mathio** [comment]
@jellevandevelde I am afraid that at the moment you will have to ship the app with both React and Vue, since our embed library is not yet decoupled from the react dependency.

**Comment by raurfang** [comment]
I think it would make sense to at least unpin the `react`, `react-dom` versions and move the declaration to `peerDependencies`. Currently two `react` versions will get bundled unless the user of the library sets the app's `react` version to the exact same version as `@typeform/embed` uses.

**Comment by mathio** [comment]
@raurfang I think you are right. I am adding this to our backlog. If you would like to open a pull request to get this done earlier we would appreciate it.

**Comment by raurfang** [comment]
Sorry, I couldn't find time earlier, thanks @osdiab @mathio for the work on this. Our bundle size is down by ~40kB thanks to #88.
I'll take a look if this can be improved further in a couple of days.

**Comment by mnapoli** [comment]
Thank you for the effort made on this issue already. I have to admit I was very surprised to see React appear in my VueJS application, all that for a Typeform popup button.

I'll be removing Typeform for now.

**Comment by osdiab** [comment]
Agreed, should at least use preact.

**Comment by Xenonym** [comment]
For anyone dealing with this issue, you can use [`preact/compat`](https://preactjs.com/guide/v10/getting-started#aliasing-react-to-preact) as a drop-in replacement for the `react` dependency. This can help shave off ~100 KB.

**Comment by mathio** [comment]
Lib version >= 1 has drastically lower file size. It is up to 90% smaller and does not have React dependency. 

I suggest you upgrade to latest version if you can.

**Comment by mnapoli** [comment]
Thank you!
