### ISSUE TITLE
How do I get onmousemove events or different events from the react component 

### ISSUE THREAD

**Issue by nachumFreedman** [Typeform/embed#255]
We are using useRef to embed the component in react underneath I saw 2 nested divs and an iframe, I tried a few different techniques to add event listeners to the current.children but nothing works, can we expose a callback. to createWidget?

**Comment by mathio** [comment]
I dont think you can listen for mouse events over an iframe for security reasons.

We currently do not plan to expose those events through the lib. What is your use case and what are you trying to achieve? Maybe I can help?

**Comment by nachumFreedman** [comment]
We are trying to record how many mouse movements the user makes throughout their form.

**Comment by mathio** [comment]
This looks like a very specific use-case and we do not see added value for many customers.

The answer from StackOverflow says it works only if the domain matches (this is enforced by browser for security reasons) and unfortunately that is not your case.

Maybe you could connect your typeform to one of analytics tools to achieve this? https://www.typeform.com/connect/c/analytics-reporting/
