### ISSUE TITLE
Add onEnd (onFinish) callback

### ISSUE THREAD

**Issue by FrontendCrypto** [Typeform/embed#282]
Hi, good afternoon. Would be possible to add a new callback `onFinish` or similar? It would be useful when opening surveys in custom modals. The idea is to be allowed to do something when button in ending page (after submitting the survey) has been clicked.

In my case I want to close my custom modal when user click the last button in the survey.

```javascript
createWidget(this.surveyIdValue, {
    container: this.bodyTarget,
    enableSandbox: this.debugValue,
    hidden: {
        name: this.nameValue,
        email: this.emailValue,
        source: this.sourceValue,
    },
    onSubmit: () => {
        // do something when survey has been submitted
    },
    onFinish: () => {
        // do something when ending page button has been clicked
        this.hideMyCustoModal()
    },
});
```

**Comment by prilutskiy** [comment]
That's an interesting case, @pcarballeda, thanks for reaching out!

@mathio WDYT?

**Comment by mathio** [comment]
I like the idea, lets put it into our backlog.

**Comment by pcarballeda** [comment]
Thank you!

**Comment by scarciofolomarco** [comment]
Hi @pcarballeda,

I contacted the team in charge of the ending screens and since the button always redirects to a new page makes the callback unusable because of the page reload.  They will look for a way to add this.

**Comment by mathio** [comment]
We have not forgotten about this feature. It took a bit longer because there were multiple people and teams involved, but its almost here! The `onEndingButtonClick` callback will be released later this week.
