### ISSUE TITLE
Typeform chat is not embedding on SPA app's components (having Nuxt Js app with client side rendering - Vue js components)

### ISSUE THREAD

**Issue by galkrisztina** [Typeform/embed#284]
Hi!

I am trying to embed the typeform chat with the `div` and `script` tags generated by the platform:

`<div data-tf-chat data-tf-tooltip="Please consult with our digital assistance" data-tf-open="load" data-tf-popover="nxUDrRT2" data-tf-button-color="#FA6B05"></div><script src="//embed.typeform.com/next/embed.js"></script>`

I have a Nuxt Js app with client side rendering (SSR = false) which means that the HTML is generated on the fly dynamically by Nuxt, and I don't have an index.html starter file where I could insert the div and the script. But even if I had, I can only insert them to a `.vue` component, because the typeform id is coming from a setting dynamically. 

I was trying to insert this to my project and to other projects as well and the chat only appeared when the div and the script were put into a static `.html` file. I also tried to insert them with the `DOM`-s `createElement` method and construct the elements with their attributes dynamically AFTER the whole component has been rendered, but the chat was not appearing. The `//embed.typeform.com/next/embed.js` script is getting the right response (I can see from Network), so probably the problem is with targeting the div when there is no SSR but I cannot understand why. When I logged the targeted div to the console, the element was already present and I also tried to construct the script tag from code after this moment but nothing happened.

Is there somebody who could solve this problem? Or is the embed.js written to work only in static html-s?

**Comment by mathio** [comment]
Hello @galkrisztina, 

we have not tested the lib with Vue framework, however a version for Vue is planned in future. In the meantime you should be able to embed using [Vanilla Embed Lib](https://github.com/Typeform/embed/tree/main/packages/embed#from-cdn).

Are you sure that the `<script>` you included in your `.vue` file is being loaded? This article suggests you might need to use a different approach when loading external JS files such as our `embed.js` lib:
https://vue-view.com/how-to-load-an-external-script-in-vue-component/

However I have tested your code in Codesandbox using a NuxtJS template and it seems to work without any issues:
https://codesandbox.io/s/tf-embed-vue-nuxtjs-9zqrc

**Comment by galkrisztina** [comment]
Hello @mathio !

Thanks for the quicky answer. Yes, I am 100% that the script is loaded because I see the request from the Network tab and the typeform's embed js is given back as the response. Yes, I see that in the example given by you is working, but now please go to the `nuxt.config.js` and on the first line of the config object please set `ssr: false`, because Nuxt apps can be used in two ways and we are using it without server side rendering as I said. (by default the ssr mode is true). And after that if you refresh the app, does it also works? Because for me not. And this is the thing I don't understand. Please look at that also in this way the embed.js is loading in network, only the chat is not appearing. It cannot find the div, which I cannot undertsand why.

Related to the vue js link you sent how to load external scripts, that is the way I also tried when I referred to "constructing the div and script tags from code with their attributes".

**Comment by mathio** [comment]
I have [modified the Codesandbox example](https://codesandbox.io/s/tf-embed-vue-nuxtjs-9zqrc?file=/pages/index.vue) to use `ssr: false` and updated the code to make the popover embed work. Excuse my code, this is my first time working with VueJS :)

You need to install the lib as dependency instead of linking to CDN. (Linking to CDN is suggested mostly for static HTML or when you are not developing in JavaScript.)
```bash
yarn add @typeform/embed
```

Then you can import the lib and necessary CSS:
```javascript
import { createPopover } from "@typeform/embed";
import "@typeform/embed/build/css/popover.css";
```

And construct the popover when your component is mounted:
```javascript
let popoverRef;

export default {
  ...
  mounted: () => {
    popoverRef = createPopover("nxUDrRT2", {
      chat: true,
      tooltip: "Please consult with our digital assistance",
      open: "load",
      buttonColor: "#FA6B05",
    });
  },
  destroyed: () => {
    if (popoverRef) {
      popoverRef.unmount(); // dont forget to destroy the popover
    }
  },
  ```

Its in the Codesandbox example: https://codesandbox.io/s/tf-embed-vue-nuxtjs-9zqrc?file=/pages/index.vue

**Comment by ricky11** [comment]
does it work with nuxt 3, i tried the above, but get an error 
500
e4.startsWith is not a function

at http://192.168.50.6:3003/node_modules/.vite/deps/@typeform_embed.js?v=7f66d855:478:33

**Comment by mathio** [comment]
Hello @ricky11 can you please provide more context? What embed code are you using? Can you provide your code or maybe reproducible example?

**Comment by ricky11** [comment]
Hello @mathio I am using nuxt 3.0, what is the best way to integrate typeform within nuxt 3? I am unable to find documentation.   Thanks.

**Comment by mathio** [comment]
I doint have much experience with Nuxt. Have you tried [the CodeSandbox example I posted above](https://codesandbox.io/s/tf-embed-vue-nuxtjs-9zqrc)?
