### ISSUE TITLE
Seemingly https related Error in embedding Typeform

### ISSUE THREAD

**Issue by zendevil** [Typeform/embed#286]
I have embedded a form in typeform in my webpage in development but it's giving me the following error:

<img width="1182" alt="Screen Shot 2021-07-06 at 2 38 50 AM" src="https://user-images.githubusercontent.com/30054030/124578752-58bd4800-de03-11eb-99f7-66e9efe8c6e9.png">

How to fix this?

**Comment by mathio** [comment]
Hello @zendevil 

We have CSP headers setup to prevent embedding on non-secure sites, but the header should be `content-security-policy-report-only` for now. It should report the CSP error in console, but not prevent you from actually embedding.

Can you please share your typeform id or URL so I can look into this further?

**Comment by zendevil** [comment]
typeform id: Z5ZNZmYN
url: https://b2aqff84ky0.typeform.com/to/Z5ZNZmYN

**Comment by mathio** [comment]
Thank you. I have just found out we are updating our CSP headers to `content-security-policy: ... frame-ancestors https: ;` (without the `-report-only` in header name). This means that the iframe will really be blocked when you embed it on a page without HTTPS. This is to protect respondents and nowadays is a standard to serve websites over HTTPS.

This can be annoying when developing on local machine and my colleagues are looking into a possibility of adding an exception in CSP headers for `localhost` served over HTTP.

I will keep you updated.

**Comment by mathio** [comment]
Our wonderful security team updated the CSP headers to allow HTTP on `localhost`:

```
content-security-policy: ... frame-ancestors http://localhost:* https:;
```

All other websites need to be served over HTTPS.
