### ISSUE TITLE
`import` issues on Netlify, SvelteKit and ViteJS

### ISSUE THREAD

**Issue by benaltair** [Typeform/embed#288]
I'm getting the following error when building on Netlify:
```
7:22:56 PM: > Named export 'createWidget' not found. The requested module '@typeform/embed' is a CommonJS module, which may not support all module.exports as named exports.
7:22:56 PM: CommonJS modules can always be imported via the default export, for example using:
7:22:56 PM: import pkg from '@typeform/embed';
7:22:56 PM: const { createWidget } = pkg;
```

This traces back to:
```ts
import { createPopup } from '@typeform/embed';
let showRegistration: boolean = false;
function openRegistrationForm() {
	showRegistration = true;
	// ID omitted from code example
	createPopup('<id>', {
		container: document.querySelector('#register')
	});
}
```

The code above works fine in the dev environment but isn't accepted by Netlify. I haven't seen it on any other libraries. Unfortunately the solution in the error message doesn't work locally (although it works in Netlify).

It's not a permalink, but you can currently see the code context at this branch: https://github.com/bahaistudies/conference/tree/netlify-identity

**Comment by mathio** [comment]
Hello @benaltair 

I think this might be an issue with SvelteKit, please see the discussion here: https://github.com/sveltejs/kit/issues/928

Also related: https://github.com/vitejs/vite/issues/3024

**Comment by benaltair** [comment]
Hi @mathio - yes, looks like Vite isn't able to handle the CJS imports well. Is ESM on the horizon for the Typeform library by any chance?

**Comment by benaltair** [comment]
Upon further inspection, the solution in the error message does indeed work:
```js
import pkg from '@typeform/embed';
const { createWidget } = pkg;
```
I'll close this for now, but would love to see ESM support for Typeform. 😊

**Comment by mathio** [comment]
I went through the docs https://nodejs.org/api/esm.html and I think our lib is ECMAScript module.

BTW It is completely fine to import the lib and use it like this:
```javascript
import tf from '@typeform/embed';
// ...
tf.createWidget(
  // ...
)
```

Could you please provide more details on what you mean by "ESM support" and what are we missing in our lib?

**Comment by benaltair** [comment]
Hi @mathio, I'm pretty unfamiliar with ES modules to be honest, but from what I understand it has to do with exports - right now only a default export is provided (I believe) and it would be nice to provide separate exports in addition the default, rather than exporting the entire module and then using dot notation.

**Comment by benaltair** [comment]
Looking closer it does look like this library is using CommonJS modules, not ES modules. 
> The Embed library is a client-side script and CommonJS module that you can use to embed your typeforms in your website or web application.
https://developer.typeform.com/embed/

What I would like to request consideration of is to provide an ES module to support more workflows.

**Comment by mathio** [comment]
I see there is `"module": "CommonJS",` in [tsconfig.js](https://github.com/Typeform/embed/blob/976eaa9d693dac9e6c2b1171d89024b49a62f78f/packages/embed/tsconfig.json#L5), however it looks like we are actually using ES modules syntax. @prilutskiy you added this config, do you have any more knowledge on this? Honestly I am a bit lost here :) Maybe its just an incorrect config?

**Comment by benmccann** [comment]
This library appears to me to be using UMD: https://github.com/Typeform/embed/blob/bc9ddcb1c515617053c9d07480037cfa4a53f714/packages/embed/webpack.config.js#L50

Rather than use UMD and try to serve both browser and server with a single build, the nicer thing to do is typically to output a CJS build specified in `main` and an ESM build specified in `module` in `package.json`

**Comment by mrisoli** [comment]
I just tried reproducing this issue with a minimal Sveltekit app and was unable to, could you provide a reproducible example? 
I used one of the latest versions of Sveltekit/Vite so maybe this issue has been fixed?
Or is the current issue to just provide multiple outputs?

**Comment by mathio** [comment]
We were unable to reproduce this. If you still experience this please feel free to reopen this with additional information.
