### ISSUE TITLE
Use popup without the button

### ISSUE THREAD

**Issue by kwiznix** [Typeform/embed#298]
Hi,

Is there a way to use the popup without the build in button?
I want to use my own button

Thanks in advance!

**Comment by mathio** [comment]
Hello @kwiznix , you can [see an example in our README](https://github.com/Typeform/embed/tree/main/packages/embed#from-cdn):

```html
<button id="button">open form</button>
<script src="//embed.typeform.com/next/embed.js"></script>
<link rel="stylesheet" href="//embed.typeform.com/next/css/popup.css" />
<script>
  const { open, close, toggle, refresh } = window.tf.createPopup('<form-id>')
  document.querySelector('#button').click = toggle
</script>
```

**Comment by kwiznix** [comment]
Hi, I am using the embed-react package

**Comment by mathio** [comment]
If you want to open the popup using a button I suggest you pass _className_ or _style_ props to the _PopupButton_ to customize it. Is there anything you are not able to achieve this way?

If you dont want to use a button at all, you can use the vanilla embed lib directly. See [an example from my article on Medium](https://medium.com/typeforms-engineering-blog/building-typeform-react-embed-sdk-e3985efccfc5#b6f2) - here the popup opens on user interaction (without a button):

```javascript
import { createPopup } from "@typeform/embed";
import "@typeform/embed/build/css/popup.css";

const MyComponent = () => {
  const openPopup = (event) => {
   createPopup("<form id>").open()
  }

  return <input type="text" onChange={openPopup} />
}
```

**Comment by mathio** [comment]
Hello @kwiznix , did this solution work for you? Can we close this or do you need any further assistance?

**Comment by kwiznix** [comment]
Yes, I used the @TypeForm/embed before and it worked perfectly and suddenly it stopped working (not showing popup, but only a small screen at the lower left side of the page), So I tried the @typeform/embed-react, since my application is in react as well. In this package it wasnt possible to use it the button I did use, so went back to the @TypeForm/embed package and found out there was a type in the css import which solved it haha, thanks for your help!

**Comment by abohannon** [comment]
For anyone else coming across this issue who needs the popup functionality without the `PopupButton`, this is what we did with our custom Button.

```
<PopupButton id="eNVhaQYU" as="span">
   <Button variant="primary">Begin survey</Button>
</PopupButton>
```

The following doesn't work, but it would be helpful if `as` took a component instead of just HTML elements. Then you could do 
```
<PopupButton as={Button} variant="primary">Begin survey</PopupButton>
```

**Comment by George3d6** [comment]
The styling of the popup from `createPopup` and that from the react-embeded button is nowhere near similar :(

**Comment by George3d6** [comment]
<img width="816" alt="Screenshot 2023-03-23 at 19 29 13" src="https://user-images.githubusercontent.com/23587658/227121762-00a56795-e0f3-479c-a4e0-b241e4f7652b.png">

This is specifically what "createPopup" would generate, with the parent being the body (set explicitly and checked in the rendered HTML), in a react app

The button worked perfectly

**Comment by George3d6** [comment]
Using the button with the `as="div"` option worked just fine though :) But a bit confusing that is the solution and it's buried, with the last one being a solution that doesn't work.

**Comment by mathio** [comment]
@George3d6 if you use `createPopup` you also need to load CSS manually. Either include it in your bundle or link from AWS (`https://embed.typeform.com/next/css/popup.css`). Then you can use any button and you will not net need to use the React wrapper `@typeform/embed-react`.

If you do use the wrapper you can use the `as="div"` and style the button as you like.
