### ISSUE TITLE
Embed JS in Chrome giving id=null error

### ISSUE THREAD

**Issue by fivesquared** [Typeform/embed#313]
![Screen Shot 2021-08-10 at 3 46 28 PM](https://user-images.githubusercontent.com/567670/128932763-79b79a4e-65de-4fd0-9e66-03e8057d6630.png)

The form gives this error after the welcome screen

**Comment by mathio** [comment]
Hello @fivesquared 

can you please share the embed code you are using so we can look into this issue?

Does this error also happen when you access the form directly via URL (without embedding it)?

**Comment by mathio** [comment]
@fivesquared can you please provide more information or can we close this?
