### ISSUE TITLE
No way to autofocus Widget

### ISSUE THREAD

**Issue by controversial** [Typeform/embed#380]
Some modalities (like Popup) autofocus when they open, but I can only autofocus the full-screen “embed” form if I use
```js
iframe.contentWindow.postMessage('embed-focus', '*')
```
However, this is undocumented so feels a bit brittle to me, and I don't want it to break if something changes about the implementation of the embedded page. Is there a better way?

**Comment by mathio** [comment]
Yes, you can use this event. We should probably document this.

**Comment by mathio** [comment]
I did some investigation in our typeform renderrer app. When `embed-focus` event is sent to the form, it enables autofocus, but does not actually focus the form. For example if you were to embed your form with `disableAutoFocus` option, you could re-enable it by sending this event. I have raised this improvement with the team responsible for renderrer app and will keep you updated here.

**Comment by controversial** [comment]
@mathio I’m still using in production the `embed-focus` method I described in my original comment, and it seems to still be working!

**Comment by mathio** [comment]
Can you please show an example? To my understanding that event only enables the auto-focus, but does not actually focus the form when fired. However all forms should have auto focus enabled by default (unless you set the *disableAutoFocus* option).

**Comment by controversial** [comment]
Sorry for the slow response—certainly, @mathio! 

We use something like the following:
```js
import React, { useRef, useEffect } from 'react';
import PropTypes from 'prop-types';
import { Widget } from '@typeform/embed-react';

export default function Page() {
  const baseRef = useRef();

  // Autofocus iframe
  useEffect(() => {
    const iframe = baseRef?.current?.querySelector?.('iframe');
    if (iframe) {
      const attemptFocus = () => iframe.contentWindow.postMessage('embed-focus', '*');
      attemptFocus();
      iframe.addEventListener('load', attemptFocus);
      return () => iframe.removeEventListener('load', attemptFocus);
    }
    return undefined;
  }, []);

  return (
    <div ref={baseRef}>
      <Widget
        id={typeformId}
        opacity={0}
        inlineOnMobile
      />
    </div>
  );
}
```

If the effect is disabled, the Widget does _not_ get autofocus when the page loads; only with the effect sending the `embed-focus` message does the typeform get focus.

**Comment by maxcountryman** [comment]
@controversial this example doesn't seem to be working for me. Both Firefox and Safari aren't setting focus as expected. I can see the iframe is being selected correctly in the hook, so I suspect the events themselves aren't quite right.

**Comment by mathio** [comment]
There was an update to the auto focus feature recently: https://github.com/Typeform/embed/pull/521

Now you dont need to post the message manually. You can use the `focus()` method returned by your embed - eg. from `createWidget`.

Also, auto focus is disabled by default for widget / standard embeds. It can be enabled via `data-tf-auto-focus` or `autoFocus: true` option.

More in my [blog post](https://mathio28.medium.com/widget-auto-focus-in-embed-sdk-8e0c0584b57).
