### ISSUE TITLE
Triggered action needs to be clear

### ISSUE THREAD

**Issue by CHEWX** [Typeform/embed#384]
Hi,

Great job with the SDK, however from a documentation point of view it's really not that clear that you can trigger an element with a custom button. The `open` param gives 4 options and none of which are triggered.

It's only after delving through comments that the only way to do this is to use the method `.open()` which isn't documented.

See also, https://github.com/Typeform/embed/issues/298

**Comment by mathio** [comment]
Hello @CHEWX 

one of the first examples in the README documents how to open a popup window on button click: https://github.com/Typeform/embed/tree/main/packages/embed#from-cdn

How would you improve the docs? Feel free to update the README and open a PR.

**Comment by CHEWX** [comment]
Sure, that's under the "From CDN" title, most would ignore that, I did anyway as it's not relevant. 

I was really looking here — https://github.com/Typeform/embed/tree/main/packages/embed#custom-launch-options

As always, will try and PR when I get time, but thought I'd reference an issue incase someone else jumps on it.
