### ISSUE TITLE
Forms not loading in IE11

### ISSUE THREAD

**Issue by jonyramos** [Typeform/embed#387]
Hi,
   I've been working on a project with **@typeform/embed** and until yesterday it worked correctly in IE11. Now we are having a problem loading the forms.

**Console output**
```
Syntax Error
vendors~form.6a663efa749ef412c805.js (9,6726)
ChunkLoadError: Loading chunk 7 failed.
(missing: https://renderer-assets.typeform.com/vendors~form.6a663efa749ef412c805.js)
Unhandled promise rejection ChunkLoadError: Loading chunk 7 failed.
(missing: https://renderer-assets.typeform.com/vendors~form.6a663efa749ef412c805.js)
```
It seems  maybe like you are not transpiling the lib **kof/animationFrame**, because there are some arrow functions in [https://renderer-assets.typeform.com/vendors~form.6a663efa749ef412c805.js](https://renderer-assets.typeform.com/vendors~form.6a663efa749ef412c805.js) 

Any idea how to fix this?
Thanks.

**Comment by mathio** [comment]
Hello @jonyramos ,

this seems to be an issue with our renderer app (that displays the form), not the embed SDK itself. I have brought it up with the team responsible for the renderer app.

Are you seeing the same issue when you access your typeform directly via URL?

**Comment by mathio** [comment]
[Officially we do not support IE 11](https://help.typeform.com/hc/en-us/articles/360029423551-FAQ) even though we try to make sure basic functionality works.

Please [contact our support](https://help.typeform.com/hc/en-us/requests/new) and they will make sure your request reaches correct team.

**Comment by jonyramos** [comment]
Thanks! i'll do that.

So is this documentation out of date? 
[https://developer.typeform.com/embed/#requirements](https://developer.typeform.com/embed/#requirements)

**Comment by mathio** [comment]
I am afraid it is. This should be the official list: https://help.typeform.com/hc/en-us/articles/360029423551-FAQ
