### ISSUE TITLE
[BUG] onClose not firing when the X on the popup form is clicked

### ISSUE THREAD

**Issue by startupmasters** [Typeform/embed#39]
I'm creating the form with .makePopup(url, options) and in the options passing 2 callback functions.

1. onSubmit - this one is working fine
2. onClose - this one is not working for me. I expect that it should fire when the "X" is clicked to close the popup form, but when clicking the "X" the form does indeed close, but the onClose function is not triggered.

**Comment by carlitosz** [comment]
@startupmasters I believe the `onClose` callback is called after the user has submitted the survey, not when the user clicks the `X`.

It would be great to have a callback when the user clicks 'X' 👍

**Comment by startupmasters** [comment]
Well, as per the documentation onClose should fire when the form is closed - "Callback function that will be executed once the typeform is closed." 

When the user submits the form, the "onSubmit" function triggers normally, but "onClose" still does not, so it does not trigger neither when submitting, nor when closing the form. I believe this is aa big.

**Comment by startupmasters** [comment]
The issue is located in api.js of the package. 

key: 'handleClose', on line 2621. the onClose() is triggered through this.props.onClose, when it should be triggered through this.props.options.onClose (because in the documentation, the callback is passed in the options object). The "onSubmit" is defined correctly on line 2661.

Changing this.props.onClose() to this.props.options.onClose() triggers the callback, BUT does not close the form itself.

One way to fix this would be to have the 'handleClose' key, fire both the internal 'onClose' (in the internal props) as well as the external 'onClose', passed in the options object when initializing. So the reworked key: 'handleClose' would be:

`key: 'handleClose',
    value: function handleClose() {
      this.props.onClose();
      this.props.options.onClose();
    }
  }`

**Comment by Gotusso** [comment]
Hi! Thanks a lot for the bug report, we'll have a look at this shortly 👍

**Comment by prilutskiy** [comment]
Hey, @startupmasters! Could you please provide a repo to reproduce the issue? I'm using the following code and everything works fine:

```html
<html>

<head></head>

<body>
  <button id="openPopupButton">Open popup</button>
  <script src="https://embed.typeform.com/embed.js"></script>
  <script>
    const btn = document.querySelector('#openPopupButton')
    btn.addEventListener('click', openPopup)

    function openPopup() {
      const TF = window.typeformEmbed
      const popup = TF.makePopup(
        'https://admin.typeform.com/to/PlBzgL',
        {
          onClose: function () {
            console.log('Typeform is closed')
          }
        }
      )
      popup.open()
    }
  </script>
</body>

</html>
```
Also, are you consuming the API from the npm registry or just from the CDN?

**Comment by prilutskiy** [comment]
Hey @startupmasters, did your problem get solved?

**Comment by prilutskiy** [comment]
@startupmasters please feel free to ping, if there any other questions

**Comment by startupmasters** [comment]
Hello, sorry for the delay. Just checked back with the team and we're using an older version ^0.9.3 so that might have been the issue. I will double-check on the newer version and get back to you.

Thanks
