### ISSUE TITLE
transitiveSearchParams doesn't properly set hide welcome

### ISSUE THREAD

**Issue by gregsj** [Typeform/embed#390]
I'm trying to hide the welcome screen depending on the referring page of my website using createWidget. However when I add `transitiveSearchParams: ["typeform-welcome=0"],` the parameter is not added to the iframe url and the welcome screen still loads.

**Comment by mathio** [comment]
What are you trying to achieve? If you want to display your widget inline on mobile see the option [`inlineOnMobile`](https://github.com/Typeform/embed/tree/main/packages/embed#options) and we will not force a welcome screen on mobile (and will not open your typeform in modal window). If you dont want a welcome screen just remove it in builder.

BTW `transitiveSearchParams` will only add params to your form if you your host page has them in URL query string as well. Name of the parameter is just `typeform-welcome` :D

**Comment by gregsj** [comment]
@mathio we have multiple paths to get to the same form. Some of the paths we want to show the welcome screen whereas others we don't. I'd like to be able to be able to set whether to show the typeform welcome screen dynamically in my code.

To do this I've tried adding the tansitiveSearchParams to my create widget function and per your suggestion to my pages URL but still see the welcome screen. Can you clarify what you think should work? Example page: https://sourcelabs.ngrok.io/anxiety (click on Start Quiz below Doctor-Designed Assessment)

**Comment by mathio** [comment]
This works as expected, params defined in `transitiveSearchParams` are correctly passed from host page URL to the form: https://glitch.com/edit/#!/lush-tide-geese
