### ISSUE TITLE
[BUG] Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten

### ISSUE THREAD

**Issue by samval** [Typeform/embed#40]
On iOS platform the cordova application don't start and in console output I see next error:

Error: Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.
Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.)

Reproduced on iOS app start.

**Comment by Gotusso** [comment]
Hi @samval,  thank you for the bug report. Would you be able to provide a sample set up for this so we can reproduce? I personally never used zone.js before but from having a quick look at the docs sounds like it's loaded too early in your project and should be delayed until other deps have been imported?

**Comment by MeirAmar** [comment]
Hi @Gotusso why you are setting / overriding Promise polyfill in case Promise is already exist on the page? can you set it as something optional?

**Comment by prilutskiy** [comment]
Hi @samval @MeirAmar 
I'm thinking about providing a way to import the package without any polyfills, as an alternative. 

For example, the following version could be used to leverage the functionality right out of the box:
```javascript
import * as TF from '@typeform/embed';
```
While the following snippet could be a solution for more advanced cases like yours, providing no polyfills/etc. at all:
```javascript
import * as TF from '@typeform/embed/pure';
```

What do you think?

**Comment by samval** [comment]
@prilutskiy let's try, please

**Comment by prilutskiy** [comment]
@samval starting from `v0.21.1` **the NPM** version of the SDK doesn't include polyfills. From no on we also mention that fact in the repo's [README](https://github.com/Typeform/embed#npm-package).
