### ISSUE TITLE
No ways to add title to Iframe

### ISSUE THREAD

**Issue by bde-maze** [Typeform/embed#400]
Hello there,

To fully pass the LightHouse test, it would awesome to be able to add a title param to the widget, like so:
`      <Widget
        title="Contact form"
        id={formId}
        style={{ width: '100%', height: '600px' }}
        className="my-form bg-gray-300"
      />`

What do you think, how can we make this happen?

Bests

**Comment by mathio** [comment]
@bde-maze @maxprilutskiy good idea, please see PR #402
