### ISSUE TITLE
Core now requiring react - no longer framework agnostic?

### ISSUE THREAD

**Issue by Godofbrowser** [Typeform/embed#403]
https://github.com/Typeform/embed/blob/main/packages/embed/src/base/iframe-options.ts#L1

This line breaks existing vuejs projects cos it now requires that react is installed.

Any help on how to fix this? Thanks in advance.

Ref error message for others who might be searching:
```
Cannot find module 'react' or its corresponding type declarations.
```

**Comment by Godofbrowser** [comment]
As a temporary fix, I've done:

create a new file `shim-react.d.ts` at the project's src/ with content:
```
/*
* Temporary fix for: https://github.com/Typeform/embed/issues/403
* */
declare module 'react' {
  type IframeHTMLAttributes<T=any> = any;
}
```

And build works again.

**Comment by mathio** [comment]
You are right, this type dependency should not be there.

**Comment by Godofbrowser** [comment]
Okay, thanks for the quick reply. I intentionally didn't want to lock the dependency version. So I'll keep the shim for now as it'll be easier for me to remember to remove that compared to remembering to unlock the dep version.

I'll watch out for the notification too. Thanks for the good work!
