### ISSUE TITLE
React <Widget> gets re-rendered even if the props don't 'actually' change

### ISSUE THREAD

**Issue by iampava** [Typeform/embed#405]
Here's a reproducible demo: https://codesandbox.io/s/muddy-tree-heduj?file=/src/App.js (just click the button and the form will re initialize completely)

I think here is the problem: https://github.com/Typeform/embed/blob/main/packages/embed-react/src/components/widget.tsx#L15-L22

There's an `useEffect` hook which has the `props` object as a param. If the reference changes, then all the code inside the hook re-runs.

**Comment by mathio** [comment]
I can see the issue. However if we remove the `props` object dependency the widget will not be re-initialized when you change its props. 🤔

**Comment by iampava** [comment]
Continued experimenting with it and sadly memoizing didn't work... It's because of the `rest` operator: `...props`. This creates a new object reference, even if the underlying props are not modified.

**Comment by iampava** [comment]
Any updates on this one? I'm curious if it's still reproducing on your end as well or am I doing something wrong
