### ISSUE TITLE
Move to a less restrictive license, like MIT

### ISSUE THREAD

**Issue by schlosser** [Typeform/embed#407]
This would make it easier for many companies to adopt; LGPL is less preferable than MIT.

**Comment by mathio** [comment]
I am not a lawyer either, but based on my understanding of [wikipedia on LGPL](https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License) you can use our library in your own source code without limitations:

> The license allows developers and companies to use and integrate a software component released under the LGPL into their own (even proprietary) software **without being required by the terms of a strong copyleft license to release the source code of their own components**. 

However if you were to fork the embed library and add any features, you are required to keep it open-source:

> However, any **developer who modifies an LGPL-covered component is required to make their modified version available under the same LGPL license**. 

As long as you install embed library as npm package you can keep your code private:

> For proprietary software, code under the LGPL is usually **used in the form of a shared library**, so that there is a clear separation between the proprietary and LGPL components. The LGPL is primarily used for software libraries, although it is also used by some stand-alone applications.

I think the statement that "_LGPL ... practically excludes usage in a closed-source project._" is false. 

However I will check with our legal department to be 100% sure.

**Comment by michaeltnguyen** [comment]
Hi @mathio, npmjs is still showing the old LGPL license.  Is there something else that needs to be done to update npm?

https://www.npmjs.com/package/@typeform/embed

<img width="318" alt="Screen Shot 2021-11-08 at 3 42 45 PM" src="https://user-images.githubusercontent.com/14219683/140822822-4dd357c3-e40a-4890-92f6-714610da7ade.png">
