### ISSUE TITLE
Auto scroll to quiz

### ISSUE THREAD

**Issue by MaxWatson94** [Typeform/embed#419]
Hey!

After the last update, I noticed that after loading the page, there is an automatic scrolling to the quiz.
Here is a sandbox example: [https://jsfiddle.net/eb9f0dcL/8/](https://jsfiddle.net/eb9f0dcL/8/)

How can we fix this?

**Comment by mathio** [comment]
Hello, automatic form focus is a feature that helps your respondents interact with your typeform more easily. 

If you want to prevent the focus (and scroll) you can use **data-tf-disable-auto-focus** attribute in your embed code.
