### ISSUE TITLE
Release embed-react/1.1.4 breaking builds

### ISSUE THREAD

**Issue by pxue** [Typeform/embed#421]
Commit: https://github.com/Typeform/embed/commit/7384691aa8e5efeb0ee02ce0f4b01df3b150ac1f creates a local reference to a package, this is incorrect in CI/CD builds.

Please revert the change as I don't see a valid reason for this change and is causing builds to fail.

@mathio

**Comment by mathio** [comment]
Sorry for the inconvenience, a new version will be released shortly.

I did not expect this would affect existing installations as dependency versions are usually defined in a lock file.
