### ISSUE TITLE
Add hideWelcomeScreen option

### ISSUE THREAD

**Issue by juliettebeaudet** [Typeform/embed#426]
Hi there!
I was looking for an option to hide the welcome screen of my typeform.
Basically would be a code equivalent of adding `?typeform-welcome=0` into the url.
Did I miss a way to do it already (I did try with transitiveSearchParams) / would you consider adding it?
Thank you for your attention!
Juliette

**Comment by mathio** [comment]
Hello @juliettebeaudet 

You can remove the welcome screen when are creating the form.

If you are talking about the "placeholder" welcome screen that is added for widgets on mobile you can use *inlineOnMobile* option ([see README](https://github.com/Typeform/embed/tree/main/packages/embed#options)).

**Comment by juliettebeaudet** [comment]
OK! Removing it from the typeform was indeed the next/last option in my mind. Thanks @mathio , have a good one!

**Comment by wyattades** [comment]
For others trying to hide the welcome screen programmatically, we were able to solve this by setting `'typeform-welcome': '0'` in the `tracking` parameter.

In React:
```jsx
<TypeformWidget
  id="123456"
  tracking={{
    'typeform-welcome': '0'
  }}
/>
```
It'd be great if this was a documented option though!
