### ISSUE TITLE
Is it possible to close the form programmatically?

### ISSUE THREAD

**Issue by redhoyasa** [Typeform/embed#438]
After the respondents have filled the form that embed using popup, I'd like to close the form instead of showing the end page of the form.

**Comment by mathio** [comment]
Hello, you can achieve this via `onSubmit` callback:

```html
<script src="//embed.typeform.com/next/embed.js"></script>
<link rel="stylesheet" href="//embed.typeform.com/next/css/popup.css" />

<button>open</button>

<script>
  document.querySelector('button').onclick = () => {
    const {open, close} = window.tf.createPopup('oWPUHPmF', {
      onSubmit: () => {
        close()
      }
    })
    open()
  }  
</script>
```

**Comment by redhoyasa** [comment]
@mathio After looking at the code, I see that `close()` isn't supported in react embed library.

Do you have a plan to support this?
