### ISSUE TITLE
OnQuestionChanged Event not fired!

### ISSUE THREAD

**Issue by abdes-zakari** [Typeform/embed#439]
OnQuestionChanged Event not fired when user navigates between form questions.

here is my code:

```
<div data-tf-widget="XXXXX"
     data-tf-hide-headers data-tf-on-ready="ready"
     data-tf-hide-footer data-tf-on-quesion-changed="changed" 
     id="form">
</div>
	<script src="//embed.typeform.com/next/embed.js"></script>
</div>
<script>
      // window.changed = () => {
      //   console.log('Question changed')
      // }

      function ready() {
        console.log('Form is ready!')
      }

      function changed(){
        console.log('Question changed')
      }
</script>
```

Do I use the OnQuestionChanged event in the right way?

**Comment by mathio** [comment]
Hello @abdes-zakari , you have a typo in your code - the attribute name should be `data-tf-on-question-changed` (you are missing a `t`). I see we have the same typo in one for the examples in our README file, I will update that as well.
