### ISSUE TITLE
Custom SVGs / images

### ISSUE THREAD

**Issue by leonardofaria** [Typeform/embed#440]
Hi

Thanks for this lib!

I am using the React package in a Gatsby application and wondering how could I customize that message icon when using in the Popover component. This is what I have now:

```jsx
      <Popover
        buttonColor="#26254D"
        height={500}
        hidden={metadata}
        id="MY-ID"
        chat
        onReady={() => {
          console.log('form ready');
        }}
      >
        Help
      </Popover>
```

I see that can customize the color but there is no good way to replace the message icon. If we had a `onLoad` event we could potentially manipulate the DOM and replace the SVG but I wonder if you plan to allow customizations of the Popover.

Thanks

**Comment by mathio** [comment]
Hello @leonardofaria. I am afraid we forgot to document this part 😃  You can pass image URL in a prop called **customIcon**.

Like this:
```
<Popover
  id="<form-id>"
  customIcon="<image-url>"
/>
```

We will update the documentation soon and then we can close this issue.

**Comment by leonardofaria** [comment]
Hi!
Thanks for letting me know :) 
I will use `customIcon`
