### ISSUE TITLE
`as` prop type definitions

### ISSUE THREAD

**Issue by bryanmylee** [Typeform/embed#447]
I'm currently using the `PopupButton` component from `@typeform/embed-react`, and passing a custom React forwardRef component into the `as` prop. Everything seems to be working perfectly, except TypeScript is complaining that `as` only supports HTML element tag names.

Is this intended behaviour?

**Comment by mathio** [comment]
Prop `as` (introduced in #373) is intended for changing the HTML tag used of the element (eg to use `<a>` instead of default `<button>`). We pass it to `React.createElement(as, {...}` to create the HTML element.
