### ISSUE TITLE
onSubmit prop in React Widget not firing

### ISSUE THREAD

**Issue by madeleinemarie** [Typeform/embed#453]
I've been using the Widget component from `@typeform/embed-react` for months now with no issues, however as of this morning the onSubmit handler has stopped firing. To test, I replaced the body of my onSubmit handler with just a console.log and am not seeing even that.

My implementation looks like: 
```
[...]

const handleSubmit = (response) => {
   console.log('submitted');
};

[...]

return (
   <Widget
        id="<id here>" // edited out, but can provide this id if necessary
        style={{ width: "100%", height: "100%", zIndex: 10 }}
        onSubmit={handleSubmit}
   />
);
```

The Results tab in the Typeform admin shows that my responses are in fact being submitted.

**Comment by fivesquared** [comment]
OnSubmit not firing in Vanilla-JS also!

**Comment by EvansJWang** [comment]
Same tested the same way, passed in a new callback and even the debugger doesnt fire inside it

**Comment by mathio** [comment]
Hello all, thank you for reporting this. We are aware about this bug and will look into it right away.

**Comment by mathio** [comment]
We identified the issue and prepared a fix. It should be deployed and available shortly. I will update you here and close the issue when it is.

**Comment by mathio** [comment]
The fix is deployed and live now.
