### ISSUE TITLE
Unable to close Popup in mobile view

### ISSUE THREAD

**Issue by dtrinh100** [Typeform/embed#455]
I imported the stylesheet from `@typeform/embed/build/css/popup.css`, which closes properly on the tablet and Desktop views, but it doesn't close nor does the cursor (if I resize the browser window) change to a pointer in the mobile view.

**Comment by mathio** [comment]
Hello @dtrinh100 I can see the close button just fine. 

![Screenshot 2022-02-05 at 12 56 25](https://user-images.githubusercontent.com/1561771/152641077-b825a518-17d1-42c3-b4ae-9bee6a00663b.png)
See demo here: https://viqt8.csb.app/

Can you please share more details? Screenshot and maybe a URL of your page? Did you check if there is some CSS from your page in overriding the close button CSS?

**Comment by dtrinh100** [comment]
So I am testing the demo in Firefox (which is also the browser that I tested my app on), I noticed the same issue as well as the popup not resizing properly with the `size` option. Here is a screenshot in the Firefox dev tool:

<img width="1421" alt="Screen Shot 2022-02-05 at 12 32 42 PM" src="https://user-images.githubusercontent.com/1930347/152652408-04795917-9454-406b-b638-5f9383790281.png">

It works fine on Chrome browsers though.

**Comment by mathio** [comment]
I can see the issue in Firefox, we will look into it.

The `size` option is applicable only to desktop. Due to limited screen size on mobile all embeds are by default displayed as full screen popup. This is to improve user experience when filling out your typeform.

**Comment by mathio** [comment]
I tested in Firefox on both Android and iOS and it works. This seems to be issue only on Firefox on desktop on very small screens (<=480px) or when using Responsive Design Mode.

This looks like something that would affect development in Firefox, but not actual users of your embedded typeform.

**Comment by mathio** [comment]
This seems to be caused by #147

**Comment by antoniofull** [comment]
Hi @dtrinh100 I tried to replicate the issue with Firefox but for me it works just fine on `Firefox 97.0.1 (64-bit)`
I can click the close icon with no problem also on small screen. Are you still experiencing the issue? 
Thanks!

**Comment by dtrinh100** [comment]
Hi @antoniofull I am still seeing the issue on my laptop, but if it works on mobile as mathio said it does, then we can close this issue. Thanks!

**Comment by antoniofull** [comment]
Thanks for let me know @dtrinh100 🙇
