### ISSUE TITLE
onSubmit not triggered on vanilla JS

### ISSUE THREAD

**Issue by DanFaudemer** [Typeform/embed#456]
We are using typeform vanilla JS in production and `onSubmit` method is no more triggered. 

A test case is available [here](https://codesandbox.io/s/ecstatic-austin-27143?file=/index.html:0-425).

Related to https://github.com/Typeform/embed/issues/453

**Comment by mathio** [comment]
Hello @DanFaudemer, thanks for reporting this.

This is not related to #453 - that one was caused by the form not sending events to embed SDK. The onSubmit callback works in HTML snippets via **data-tf-on-submit** but seems to be broken in JS embeds.

We will investigate.

**Comment by mathio** [comment]
You have `enableSandbox: true` in your typeform embed. Submissions are disabled in sandbox mode and therefore the event is not dispatched. 

@DanFaudemer  did this work in sandbox mode before?

**Comment by mathio** [comment]
@DanFaudemer we are looking into it and we will reactivate this for sandbox too. Sorry for the inconvenience.

**Comment by julianwitzel** [comment]
@mathio Is this now updated so that you can test event tracking in sandbox again?
