### ISSUE TITLE
scroll question

### ISSUE THREAD

**Issue by baesumin** [Typeform/embed#481]
Is there a way to prevent mouse wheel scrolling inside a typeform?

**Comment by mathio** [comment]
Hello this is currently not possible. Scrolling is one of the features to navigate between questions. Why do you want to disable it? What is your use case?

**Comment by baesumin** [comment]
Hello. When a widget is attached to the homepage, when the homepage is scrolled with the mouse wheel, if the mouse is in the widget area, the widget is scrolled. I want to prevent the widget from scrolling with the mouse wheel even when the mouse is pointing at the widget.

**Comment by mathio** [comment]
Hi, I will talk to our UX designers to see if we can provide a setting to disable this feature.

**Comment by baesumin** [comment]
thank you!

**Comment by mathio** [comment]
I am happy to let you know this feature was just released. You can use it via config option `disableScroll` / `data-tf-disable-scroll ` like this:

```html
<div data-tf-widget="<id>" data-tf-disable-scroll style="height:500px;"></div>
<script src="//embed.typeform.com/next/embed.js"></script>
```
