### ISSUE TITLE
Can't we just reset the localStorage instead of making multiple API calls 

### ISSUE THREAD

**Issue by Abhishek765Flyfin** [Typeform/embed#482]
Hi, I've used the **createSlider** method to create the Typeform manually (Like after some action), Here's the sample code:
```js

// For Creating a TypeForm Embed
export const createTypeFormSlider = (typeFormID) => {
  if (typeof window !== 'undefined') {
    const sliderRight = window.tf.createSlider(typeFormID);
    sliderRight.toggle();
    if (document.querySelector('.tf-v1-iframe-wrapper')) {
      document.querySelector('.tf-v1-iframe-wrapper').style.height =
        'calc(100vh - 4.125rem)';
      document.querySelector('.tf-v1-iframe-wrapper').style.marginTop =
        '4.125rem';
    }
  }
};
```

**- The issue is -> it is performing a set of API calls on each action and recreating the localstorage again and again (Instead of just resetting the fields)**

Sometimes it is taking a lot of time to boot up the main TypeForm UI

<img width="736" alt="image" src="https://user-images.githubusercontent.com/88670079/156924282-3a12383f-3515-4aac-9a4e-6e18498acb70.png">

_**can't we cached these Scripts and reuse them on every action??**_

Thanks

**Comment by mathio** [comment]
Hello @Abhishek765Flyfin those JS scripts are required for by your typeform to work. It should be cached by your browser (when you open dev tools in your browser caching might be disabled) and will be loaded from cache on subsequent visits.

Is your embedded typeform performing poorly? Do you have a link where I can have a look?
