### ISSUE TITLE
PopupButton autoClose does not remove the overflow: hidden from body

### ISSUE THREAD

**Issue by ilyem** [Typeform/embed#486]
Issue:  Using autoClose for the PopupButton component removes the form modal but not the   overflow: hidden from the body.
onClose does not trigger on autoClose, to track the event and manually remove the  overflow: hidden style from the body.

Version: 1.13.0

**Comment by mathio** [comment]
Thanks for reporting, we will have a look.

**Comment by mathio** [comment]
I tested with latest `PopupButton` component and it works. See CodeSandbox here: https://codesandbox.io/s/fragrant-leftpad-3m1ky8?file=/pages/index.js

If the issue still persists feel free to reopen this issue with code to reproduce it.

**Comment by connorjacobsen** [comment]
Sorry I don't have time to get you code right now, but it appears using the react library in a NextJS app and setting an `onSubmit` callback results in the `overflow: hidden` not being removed from the body element.

```
"@typeform/embed-react@^2.12.0":
  version "2.12.0"
  resolved "https://registry.yarnpkg.com/@typeform/embed-react/-/embed-react-2.12.0.tgz#82c059686d9342c8f4d1ea720b3fa4a1f931dbf9"
  integrity sha512-SJmoZZNbHu5JZ+sReK8u1NZq8MluoDDcECFzQmCmlkkbrjEMrlWE8wqpI2Jcd8aoa3rn9OtR+IEWaMkPf2fIGQ==
  dependencies:
    "@typeform/embed" "2.6.1"
    fast-deep-equal "^3.1.3"

"@typeform/embed@2.6.1":
  version "2.6.1"
  resolved "https://registry.yarnpkg.com/@typeform/embed/-/embed-2.6.1.tgz#51fa61ea66de0f8a221abe1e2e862b44dc62b519"
  integrity sha512-dXiyu+nr4vuVjfGcYeCGODyDEsSzF2JXKw0g0ZTbuKDqYn+0/q94o1dDO6xDijG0ThWZNZZKgIsBkckF4miEkg==```

**Comment by mathio** [comment]
Hi @connorjacobsen ,

the `onSubmit` callback is not supposed to close the popup. 

I just tried it here and it works as expected: https://codesandbox.io/s/autumn-worker-tgsumk?file=/src/App.js

Maybe you are not wrapping the `onSubmit` handler in `useCallback` and as you change your component state the function actually changes? The embed is reloaded on prop change and unfortunately this also removes the popup iframe element.

**Comment by timpetri** [comment]
Observing the same thing in a nextjs app.
