### ISSUE TITLE
Popover question.

### ISSUE THREAD

**Issue by restcristian** [Typeform/embed#488]
Hello, it is the first time that I use this plugin, so I was wondering if I wanted to render a popover instead of a popup, do I have to enter an specific prop? or with the id should be enough?  I do not see any obvious prop, and when I try only with the ID I get from the new generated script, it still renders the popup.

**Comment by mathio** [comment]
Hi 👋  For popup you need a code like this. You need to provide a button that will open the popup when clicked:

```
<button data-tf-popup="<FORM-ID>">click me</button>
```

For popover we provide the button for you (you can customize the icon), you just need to initialize it:

```
<div data-tf-popover="<FORM-ID>"></div>
```

**Comment by restcristian** [comment]
I see thanks. I forgot to mention that I am using this library: I dont know if there is a way to tell it that we should use a poppup
https://www.npmjs.com/package/@typeform/embed-react

**Comment by restcristian** [comment]
Oh I see there is a popover component in the library. I will try that. Thanks :)
