### ISSUE TITLE
 The form and time reset when the window is resized in the browser

### ISSUE THREAD

**Issue by AdrianAexol** [Typeform/embed#489]

**Comment by mathio** [comment]
Hi, we will need more info than this. Ideally some code we can use to reproduce this issue.

**Comment by krry** [comment]
We have a similar situation. Embedding a Typeform with `embed-react` and its `Widget` component, when the browser window is resized, the Typeform (or its encapsulating `iframe`) reloads, which starts the survey over.

**Comment by patrick-samy** [comment]
Exact same issue here. Has anyone found a workaround?

**Comment by mathio** [comment]
It is hard to say without seeing the code, but you are most likely passing some props to the `Widget` component that change on browser resize. React will re-render the component on props change - in this case it means re-rendering the iframe which causes your typeform to be reloaded. 

Unfortunately there is no workaround for this one yet, but maybe when #496 is ready you could restart your respondent progress where they left off?
