### ISSUE TITLE
Jump to question

### ISSUE THREAD

**Issue by chandlerroth** [Typeform/embed#496]
I would love to be able to take the output of the block ref from the `onQuestionChanged` callback to be able to jump back to that question if the user reloads the page or form. 

My scenario: I've got a Typeform with over 100 questions. Its great that Typeform saves the responses to these questions in `localStorage`, but I'd like to jump to the last question they responded to if the page reloads (because otherwise the user has to click through whatever questions they've already answered, which is annoying!).

**Comment by mattrobinson10** [comment]
Hi 👋, thank you for raising this. A feature like this is under consideration for our roadmap this year, we will let you know when something is planned

**Comment by chandlerroth** [comment]
@mattrobinson10 awesome, thank you! :)

**Comment by chandlerroth** [comment]
@mattrobinson10 is there anything I could do to help out with this, or are there internals that have to be wired up in order to expose useful interfaces to this embed repo? One thought I had was the "Submit" button returns a user to a question with an error -- perhaps that's functionality to build on top of -- but I assume that's all internals of Typeform, right?

**Comment by mattrobinson10** [comment]
@chandlerroth yes you are correct, there will need to be some modifications to the typeform app itself, so that will need to be worked on internally. Thank you for the offer though, it's much appreciated!

**Comment by chandlerroth** [comment]
This is still a need we have! Would make for a much smoother UX if a user didn't fill a very long form out, and had to refresh.

**Comment by mathio** [comment]
Hello, unfortunately the request was not picked up for the roadmap so far. It has been communicated to the product team however we can not commit to any deadlines at the moment. If the feature is developed, it will be communicated through standard channels, eg [Typeform Community](https://community.typeform.com/).

**Comment by BEN00262** [comment]
Any progress on this issue?

**Comment by mathio** [comment]
Hello @BEN00262,

unfortunately this feature has not been planned. I do not have any dates to share nor can I confirm if this feature will be developed.

An alternative approach for forms with a lot of questions might be splitting your questions across multiple forms. You can detect which forms were submitted already and let your respondents continue with the subsequent form. I know it is not a 100% solution, but it is close.
