### ISSUE TITLE
keepSession option relying on third party cookies

### ISSUE THREAD

**Issue by camro** [Typeform/embed#501]
The `keepSession` option seems to be relying on third party cookies, which Chrome is blocking by default. Would it be possible to rely on a first party cookie instead, such as using the domain the embed is running on?

**Comment by mathio** [comment]
Hello @camro 

sorry for a late reply. The feature is not using any additional cookies. If you supply `keepSession` option to your typeform the lib will just hide it via CSS when closing - the form will not be removed from the page as it is without this option. Re-opening the form should be instant.
