### ISSUE TITLE
How to get selected answer for multiple choice typeform question when user submits an answer

### ISSUE THREAD

**Issue by henok-outlier** [Typeform/embed#505]
<img width="652" alt="Screen Shot 2022-06-18 at 6 37 30 PM" src="https://user-images.githubusercontent.com/72997506/174445801-15bcffc7-3261-460c-ba11-7b40ee19f3fd.png">

I've a multiple choice type question in one of typepform questions, and we want to track when user submits an answer for questions, but currently I couldn't find a way to get the selected answer.

```
import { Widget } from "@typeform/embed-react";
import "./styles.css";

export default function App() {
  return (
    <div className="App">
      <h1>Hello Outlier</h1>
      <h2>Start editing to see some magic happen!</h2>
      <Widget
        id="KeCRt5S6"
        className="my-form"
        style={{ width: "100%", height: "100vh" }}
        onQuestionChanged={({ ref }) => console.log(ref)}
      />
    </div>
  );
}
```

I use this code to render my typeform widget.

**Comment by mathio** [comment]
Hello @henok-outlier 

you can no read answers in `onQuestionChanged` because it is not submitted yet. You can retrieve form responses after your typeform is submitted. I wrote a [blog post about integrating embeds with responses API](https://medium.com/typeforms-engineering-blog/integrate-typeform-with-next-js-b27a5306bfbb) that might help you.

In short:

1. embed form
2. use an `onSubmit` callback
3. [fetch responses](https://developer.typeform.com/responses/) via custom proxy endpoint

**Comment by henok-outlier** [comment]
Hi @mathio , thanks for your reply. Yes, I can able to get submitted responses, but I would like to know when user answers one question from list of questions. So in my typeform embed I've 3 questions, and would like to track what user select for a specific question before submission.

I see that typeform stores selected answers in local storage, so that when we close the form and open it in different time, it still remembers user selections and was curios where typeform is saving user selections, and I saw that it's in local storage and couldn't able to read it because it's stored in different domain. Is there a way to get partial responses either from local storage or through some api calls? Thanks!

<img width="1044" alt="Screen Shot 2022-06-20 at 8 32 48 AM" src="https://user-images.githubusercontent.com/72997506/174658393-8a64c281-8711-4cbe-b50b-d8756d9c99a9.png">

**Comment by mathio** [comment]
Unfortunately this is not possible at the moment.
