### ISSUE TITLE
Send the ending screen reference on callbacks

### ISSUE THREAD

**Issue by Hooandee** [Typeform/embed#514]
Hi! 

I would like to know if it's possible to send the reference of the ending screen the user is visiting after they submit the form. I need to create some funnels on a Data platform but I'm not able to get the ending screen reference the user is landing after they submit.

I've tried to use `onSubmit` but it does not includes the value, nor `onQuestionChanged` because the ending screen is not a question per se. The only one I could use is `onEndingButtonClick` but it does not carry the reference of the ending screen and maybe customers will leave the form without clicking the CTA.

Is it possible to trigger the `onQuestionChanged` event with the reference of the ending screen on ending screens? 

Thanks!

**Comment by mathio** [comment]
This is an internal company request and should be reported through appropriate channels.
