### ISSUE TITLE
A11Y issue with embed not having a title

### ISSUE THREAD

**Issue by claudialigidakis** [Typeform/embed#522]
Hello,

I'd like to add a `title` or `ariaLabel` to the iframe within the embed as an optional prop. This will solve the component from failing within axe-jest.

Thanks!

**Comment by mathio** [comment]
Hello @claudialigidakis 

you can pass any props / attributes to the iframe in `iframeProps`. Like this:

```
<div data-tf-widget="<id>" data-tf-iframe-props="title=Welcome to my form"></div>
```

Or with JS API:

```
window.tf.createWidget('<id>', {
  container: document.querySelector('#wrapper'),
  iframeProps: {
    title: 'Welcome to my form',
  }
})
```

[You can also see how it works in this example.](https://glitch.com/edit/#!/tf-iframe-props-a11y
