### ISSUE TITLE
Hidden fields missing

### ISSUE THREAD

**Issue by joshharington** [Typeform/embed#524]
I am using the embed SDK to embed a typeform into a page,  passing through hidden fields using data-tf-hidden, but they dont get added to the typeform URL, and not present in the hidden fields in the responses of the typeform.

My code:
```
<div
                        class="typeform-quiz-container"
                        data-tf-widget="<?php echo $custom_fields['quiz_typeform_id']; ?>"
                        data-tf-hidden="user_id=<?php echo get_current_user_id(); ?>"
                        data-tf-inline-on-mobile
                        data-tf-on-ready="tfReady"
                        data-tf-on-submit="tfSubmit"
                        data-tf-on-question-changed="tfChanged"
                        data-tf-on-height-changed="tfhChanged"
                    ></div>
```

The variable and field are getting set in the div as documentation states
![Page source](https://user-images.githubusercontent.com/10532582/194317442-133da4c9-97d2-4780-9ebb-42f6e74756ab.png)

When going to the Responses for this typeform, you can see that the fields arnt going through.
![Results on typeform](https://user-images.githubusercontent.com/10532582/194317800-7f060f34-dc6b-4dc0-a8e6-4a413ba31fc4.png)

I have added the hidden fields as per the documentation:
![Set Hidden fields](https://user-images.githubusercontent.com/10532582/194318040-8a308785-7886-437c-b132-042862be1acf.png)

I am wanting to get the fields back when I pull the results, but it's still returning ```hidden: {}```. I have tried setting multiple hidden fields `user_id`, `name`, `email`, `user` and more. I have also tried setting the hidden fields in different sequences and combinations. Tried passing through just the user_id, or name, tried combined with multiple fields as well

```
data-tf-hidden="user_id=<?php echo get_current_user_id(); ?>"
data-tf-hidden="user_id=<?php echo get_current_user_id(); ?>,email=<?php echo get_current_user()->user_email; ?>"
```

Any ideas?

**Comment by mathio** [comment]
I tried with your code and I can see the `user_id` hidden field is passed to the form URL correctly in the DOM:

![Screen Shot 2022-10-06 at 15 04 35](https://user-images.githubusercontent.com/1561771/194320262-0e02e346-1440-45f6-adf4-e1ff51265e28.png)

Can you confirm the hidden field is passed to your iframe as well?

**Comment by joshharington** [comment]
@mathio yes it is being passed into the form URL in the DOM, the iframe src at the end has #user_id=399

**Comment by mathio** [comment]
Can you please try with a different hidden field name? Maybe `user_id` name is a reserved name and is clashing with some internal variables? 🤔

**Comment by joshharington** [comment]
I have tried using `name`, `email`, `user_id`, `user` as well as other ones. When testing now, if I add `email`, and `user` at the same time, it shows, but when using `user` on it's own it isnt showing. When using mutliple fields though and partials come through (only happening now, wasnt happening earlier), user_id isnt coming through at all, most likely reserved somewhere

**Comment by mathio** [comment]
I will check with respective team if there are any possible name clashes like this. 

In the mean time I would suggest renaming problematic hidden fields (`user` and `user_id`) to get unblocked immediately.

**Comment by mathio** [comment]
@joshharington can you please share your form id / URL? Please also share your full JS embed code if you can. And if you have a public website with your typeform it will help too. We will have a look.

**Comment by mathio** [comment]
Hello @joshharington are you still experiencing this issue?
