### ISSUE TITLE
[Question]: Typeform embed react - on submit 

### ISSUE THREAD

**Issue by malatinigreenly** [Typeform/embed#529]
Hello ! 
I am working on a React project, using the Widget component from "@typeform/embed-react". 

There are some typeform results that I would like to avoid (not store / save at all): when a demo or admin account answers the form, I would like to act like it has been answered to show the behavior to our clients, but I would like to not have the answer in my form's results. 

I tried to avoid using the "onSubmit" props of the Widget component, but i can still find the submission in my results. 
Is there a props or other way to "indicate to the component" to not save the answer in the form's results please ? 

Thanks for you help !
Best regards !

**Comment by mathio** [comment]
Hello @malatinigreenly,

you can achieve this by adding `enableSandbox` attribute to your embed to [enable sandbox mode](https://www.typeform.com/help/a/test-your-typeforms-without-creating-an-entry-for-advanced-users-360029295952/).This will disable submissions and tracking in the embedded form.

Logic in `onSubmit` is executed only after the form has been already submitted.

**Comment by malatinigreenly** [comment]
Hello @mathio ! Thanks a lot for your answer ! I am going to try this :) Have a great day!
