### ISSUE TITLE
Any way to change the hidden field in the onReady callback?

### ISSUE THREAD

**Issue by jaulin** [Typeform/embed#531]
Hello,

I am trying to find a way to access the hidden field in one of the callback functions but there doesn't seem to be a way to do so.

```
  const { open } = window.tf.createPopup('blabla', {
      onReady: () => {
        this.hidden['time_pop_up_opened'] = Date.now(); <--- is there a way to do something similar here?
      },
      hidden: {'time_pop_up_opened': 0}
  });
```

I want to do this because I want to get the exact time the pop up opened and pass it across. I know there is a `landed_at` field but this isn't what we want as this time is when the user first interacts with the form, not when the form loads up. For example, the form can pop up but it can stay on the screen for 10 minutes before the user comes back and interacts with it.

**Comment by mathio** [comment]
Hi @jaulin 

unfortunately you can not change the hidden field once the embed has been created. 

However in your case you can create the popup on click (right before it is opened), like this:

```js
const openPopup = () => {
  const { open } = window.tf.createPopup('blabla', {
      hidden: {
        'time_pop_up_opened': Date.now()
      }
  });
  open()
}
```

**Comment by jaulin** [comment]
> Hi @jaulin
> 
> unfortunately you can not change the hidden field once the embed has been created.
> 
> However in your case you can create the popup on click (right before it is opened), like this:
> 
> ```js
> const openPopup = () => {
>   const { open } = window.tf.createPopup('blabla', {
>       hidden: {
>         'time_pop_up_opened': Date.now()
>       }
>   });
>   open()
> }
> ```

That's brilliant, this works exactly how we want it to. Thanks for solution and quick reply 👍
