### ISSUE TITLE
How to open Typeform on Webview Android

### ISSUE THREAD

**Issue by argaasasta** [Typeform/embed#543]
i put setting on webview like this

            settings.javaScriptEnabled = true
            settings.javaScriptCanOpenWindowsAutomatically = true
            settings.allowContentAccess = true
            settings.domStorageEnabled = true
            settings.cacheMode = WebSettings.LOAD_DEFAULT
            settings.mediaPlaybackRequiresUserGesture = true

But when i open the webview on Android, it stop on loading
![image](https://user-images.githubusercontent.com/10597882/205600535-ff2283d7-420d-4899-9ee1-dc64aef0b5ed.png)

**Comment by mathio** [comment]
What page or URL do you open in the webview?

**Comment by argaasasta** [comment]
@mathio this Page https://form.typeform.com/to/kyXhYMb6

**Comment by mathio** [comment]
Is it a blank screen or can you see the loading animation (as in your screenshot)?

**Comment by argaasasta** [comment]
@mathio yes i can see the loading animation, but after that, it will blank white

**Comment by argaasasta** [comment]
@mathio it works on WebView Accompanist https://google.github.io/accompanist/web/. Maybe i will use this.

**Comment by joycevherck** [comment]
Hi @argaasasta - are you able to provide any dev tools errors? Either console errors or network errors. Thanks

**Comment by argaasasta** [comment]
@joycevherck sorry, no error that i found on chrome://inspect on my device

**Comment by WestFR** [comment]
This issue still exists with `AndroidView` with compose

Fixed with : 
```
    layoutParams = ViewGroup.LayoutParams(
                            ViewGroup.LayoutParams.MATCH_PARENT,
                            ViewGroup.LayoutParams.MATCH_PARENT
                        )
```
