### ISSUE TITLE
Need the ability to disable save partial completion

### ISSUE THREAD

**Issue by geoguide** [Typeform/embed#557]
For security purposes, we need the ability to disable the saving of partial completion. I commented on the [previous issue](https://github.com/Typeform/embed/issues/215) but it did not re-remove the stale tag. Is there any way to accomplish this or is the feature coming out soon? Thanks.

**Comment by mathio** [comment]
Hi @geoguide , sorry about the `stale` tag. I removed it. Let's continue the conversation there: https://github.com/Typeform/embed/issues/215
