### ISSUE TITLE
Integration with React Native?

### ISSUE THREAD

**Issue by ClaudionorJunior** [Typeform/embed#563]
Today in our team, we are studying a way to implement Typeform in our APP to speed up some demands, but we would like to know if anyone knows or has had any experience with this integration in React Native?
Thanks team.

**Comment by mathio** [comment]
Hello @ClaudionorJunior ,

unfortunately our lib does not support react native. To embed in react native apps you need to place your typeform into a [webview component](https://reactnative.dev/docs/0.61/webview), eg:

```javascript
<WebView source={{ uri: `https://form.typeform.com/to/${formId}` }} />
``` 

If you want any advanced functionality (eg. embed as popup), you will need to build it yourself.

You can [use the lib in progressive web apps with wrappers like Capacitor or Cordova](https://www.typeform.com/developers/embed/mobile-apps/).

**Comment by HimanshuCF** [comment]
@mathio Hey can you please tell me how to send hidden params here. Thanks

**Comment by mathio** [comment]
Hi @HimanshuCF , you can pass them via URL hash / fragment - `#name=value`.

For example:
```
https://successteam.typeform.com/to/nzthWI#name=John+Doe&source=Foobar
```

See help center article for more info: https://www.typeform.com/help/a/using-hidden-fields-360052676612/
