### ISSUE TITLE
@typeform/embed-react shows a Welcome Page that should not exist (on mobile)

### ISSUE THREAD

**Issue by mphasize** [Typeform/embed#570]
Hello there, 

I'm experiencing an interesting issue, when I'm embedding a Typeform into a website with the `@typeform/embed-react` library. I'm using hidden fields to show custom data inside the form and inside the Typeform editor the first element of the form is a question. There are no Welcome Screens configured.

On desktop everything works as expected and the form jumps directly to the first question.
However, on mobile, the first thing I see is a Welcome Screen with a Start button. Only after tapping start, do we get to the first question.

Is this intended or are there any known workarounds?
Any help would be appreciated. :) 
Thanks

**Comment by mathio** [comment]
Hello @mphasize , yes this is intended behavior. Please read more about it in our help article:

[https://www.typeform.com/help/a/welcome-screen-360052366812/](https://www.typeform.com/help/a/welcome-screen-360052366812/#:~:text=How%20to%20skip%20the%20Welcome%20Screen%20on%20mobile)

You can use `inlineOnMobile` prop to disable this behavior and display your typeform inline on mobile devices instead of opening in a fullscreen modal window ([see related demo](https://codesandbox.io/s/github/Typeform/embed-demo/tree/main/demo-html/widget-inline)):

It should be as simple as this:
```jsx
<Widget id={yourTypeformId} inlineOnMobile />
```

**Comment by mathio** [comment]
You are welcome. No worries, we are here to answer questions like that.

Do you think it would help to update the react lib (or the other) README with the link to the help article?

**Comment by mphasize** [comment]
That would definitely help. What would be really fantastic would be to document the available options and their naming as React props. In the linked documentation, the example given is `<div data-tf-widget="ABCDEF" data-tf-inline-on-mobile></div>` but as you pointed out in your comment above, the React prop is called `inlineOnMobile`.
Actually, the table of config options mentioned in the "Vanilla JS" docs is really helpful  (https://github.com/Typeform/embed/tree/main/packages/embed) – maybe just clarify that (some of?) these options are available as React props? In any case, thanks for the help, what I was trying to do is working now. :)

**Comment by mathio** [comment]
Actually all the options from vanilla lib are available as props, [as mentioned in the react lib README](https://github.com/Typeform/embed/tree/main/packages/embed-react#options) 😄

**Comment by mphasize** [comment]
Oh my, I must've been blind that day. I'm sorry.

**Comment by dsims** [comment]
@mathio Is there an reason as to why fullscreen-on-mobile requires a placeholder screen? The help article doesn't explain.

**Comment by mathio** [comment]
In order to open the form in fullscreen modal on mobile devices, the "start" button on welcome screen is how you open the form in the modal. 

If you'd prefer not to open the form in full screen and hide the welcome screen, you can use `inlineOnMobile` option.
