### ISSUE TITLE
Cannot detect ending screen

### ISSUE THREAD

**Issue by elbro** [Typeform/embed#584]
We have two ending screens for a quiz, one where a score is above threshold and one for a 'failure'.

We can detect button click in these screens via onEndingButtonClick, but unfortunately cannot discern which screen it came from, nor access the 'score' value from onSubmit (or anywhere else)

Huge blocker as we cannot use a URL redirect in our React SPA

**Comment by mathio** [comment]
Since responses are processed asynchronously we are unable to provide any values from the response in `onSubmit` callback. A possible solution would be to fetch the response server-side using our [Responses API](https://www.typeform.com/developers/responses/). You can find [a tutorial on how to do with in this blog post](https://medium.com/typeforms-engineering-blog/integrate-typeform-with-next-js-b27a5306bfbb).

As for the `onEndingButtonClick` callback - we currently do not pass the `ref` of ending screen to the embed. However this is a good feature request and we will think about it in future.

**Comment by elbro** [comment]
Thanks. Yeah, a really awesome feature that solves this for us is for `onEndingButtonClick` to simply know which Ending screen was hit, A, B or C in this case; 
![image](https://github.com/Typeform/embed/assets/4560065/3a341e4e-69b6-4037-a95b-524474ae735b)
Would this be hard to implement?

**Comment by mathio** [comment]
The embed SDK part is not that complicated, however there will need to be some modifications to the typeform app itself. I will talk to the team and put this feature request into our backlog.

**Comment by nirajniroula** [comment]
Huge blocker for me too. I've been trying to determine the lead status based on user answers, and the only approach I found is using the [Responses API](https://www.typeform.com/developers/responses/). However, this method is not very efficient and straightforward. With this approach, I found a couple of options to determine the lead status:

- Checking the number of questions and/or question/answer combinations (which might require code changes for every typeform update).
- Using quiz scores (which doesn't require code changes, but it requires assigning scores during typeform updates, and if there's existing branching and calculation logic, the quiz score is not available).

If there are any other better options that I might have missed, please let us know. 
Additionally, as discussed in this thread, I also believe the ability to pass the reference of the ending screen to the `onEndingButtonClick` callback would provide great value to the package.

**Comment by mathio** [comment]
This change will be released soon. After we start sending `ref` in payload the PR #597 can be merged to update types.

**⚠️  Note:** The `ref` value will be available in `onEndingButtonClick` callback payload for [plans with "Redirect from ending screen" feature](https://typeform.com/pricing) (currently plans Plus and above). Basic and free plan will not receive `ref` value in the payload.
