### ISSUE TITLE
Customize Text colour and Button size - Typeform user feedback (Sidetab)

### ISSUE THREAD

**Issue by ibrahimshbat** [Typeform/embed#586]
I am implementing Typeform user feedback (Sidetab) in React using @typeform/embed-react library as following:

//In React I use the bellow code

<Sidetab
        id={formId}
        hidden={{
          user_id : me.id,
          name: me.first_name,
        }}
        ref={sidetabRef}
        medium="demo-test"
        buttonText="Send us feedback"
        buttonColor="#ffa366"
/>
All looks good so far, the only issue is that I have not found a way to change text colour in Button or the button size. It seems there is no fields/props in Sidetab component to change button text colour/font and button size.

**Comment by dmytromykhailov** [comment]
Thank you for your feedback. Indeed, these settings are not supported at the moment. 
We are taking this as a feature request.
