### ISSUE TITLE
shareGaInstance not working with NextJs

### ISSUE THREAD

**Issue by elbro** [Typeform/embed#588]
Loading GA tag the proper way in NextJs and setting shareGaInstance prop gives this error: `Whoops! You enabled the shareGaInstance feature in yourtypeform embed but the tracker with ID G-CLB8J230JC was not found. Make sure to include Google Analytics Javascript code before the Typeform Embed Javascriptcode in your page and use correct tracker ID`

Google Analytics is loaded using Next's <Script> tag in _app.js, and the bundle including the npm package is loaded early on in the <Head>. I've tried to load the GA script earlier (which negatively affects the whole site) but still always get the same error.

I've also tried to Lazy load this library or via CDN script (so it loads after GA) but with no luck so far.

Has anyone managed to get this working with Next? it's a shame this is so fragile

**Comment by mathio** [comment]
Hello, can you please share the code of how you are loading the GA tag in your NextJS app? I will look into this.
