### ISSUE TITLE
Correct usage of "container"?

### ISSUE THREAD

**Issue by pehrlich2** [Typeform/embed#602]
I'm migrating from data- elements to the `createWidget` API.  This is so that the user can enter their email on the main page and have it pre-populated.  The easiest way to do this might be if I could just write to the `data-` attributes and have that either auto-detected, or call some api to have it ingest the new config.

According to the a forum post I saw, the recommended way of doing this is a full `createWidget` API.  But in doing so, I'm not sure the right value of "container" to use - it seems like I will loose the slick css transition and dimming of the background unless I rebuild that myself?

Feel free to close this issue as it's blurring the line of tech support vs valid issue :)

**Comment by mathio** [comment]
Hello @pehrlich2 

the value of `container` is just a DOM element (usually div) where you would like to inject the snippet.

If you have a HTML embed like this:
```html
<div id="wrapper" class="nice-form" data-tf-widget="<id>" data-tf-...></div>
```

You can convert it to JavaScript embed like this:
```html
<div id="wrapper" class="nice-form"></div>
<script>
  const container = document.querySelector("#wrapper")
  window.tf.createWidget("<id>", { container })
</script>
```

This should preserve all other CSS or logic you might have attached to the container.

---

Alternatively, if you'd like to keep using your existing embed code with `data-tf-` attributes and it is the only form on your page, maybe you could try to use `window.tf.reload()` ([see docs](https://github.com/Typeform/embed/tree/main/packages/embed#loading-and-reloading-embedded-forms)) after you modify the snippet to reload your typeform with new data. Or if there is no typeform in the page, just call `window.tf.load()` after you inject the snippet into your page.

**Comment by pehrlich2** [comment]
Brilliant `window.tf.reload` did just what I was looking for. Thanks!
