### ISSUE TITLE
Adding an SVG inside the PopupButton component results in a error when any page interaction happens

### ISSUE THREAD

**Issue by bridie** [Typeform/embed#604]
When an SVG from the `@heroicons/react/outline` library is added as a child to the PopupButton component a `Maximum call stack size exceeded` error occurs whenever the page is interacted with at all.

This doesn't happen locally when using the dev server, it only happens on a production build.

This is the component:

```
<PopupButton
    id="1"
    size="80"
    hidden={{ email: this.state.username, deals: this.state.deals }}
>
    <QuestionMarkCircleIcon
        className="w-5 h-5 text-primary"
        aria-hidden="true"
    />
    Help me choose
</PopupButton>
```

**Comment by mathio** [comment]
Hello @bridie,

Sorry for the late reply.  I just tested this with both standard SVG and `@heroicons/react` lib and it works as expected.

See code here: https://glitch.com/edit/#!/tf-embed-heroicon?path=src%2Fpages%2Fhome.jsx%3A71%3A44
