### ISSUE TITLE
Enable pre-loading of a typeform

### ISSUE THREAD

**Issue by shravanikandadai** [Typeform/embed#625]
Hi,

I would like to know if it is possible to pre-load a form and display it when necessary. Right now, though the form is mounted to the DOM, it only loads when the DOM element to which the form is added to is physically visible.

**Comment by mathio** [comment]
Hi @shravanikandadai 

for which embed types would you want this?

Note that it might mess up your metrics, because preloading would count as a visit even though the form would not be visible (yet).

**Comment by shravanikandadai** [comment]
Hi,

Thank you for a quick reply.

It would be great if this feature is available for all types of embeds as I’m using both inline and modal types in my App.

Thank you for the heads-up. I will plan a logic to deal with it.

Regards,
Shravani Kandadai.

**Comment by mathio** [comment]
The inline embed (when displayed out of the current viewport, eg "below fold") is preloaded automatically.

I can see this might be valuable for other embed types.

@shravanikandadai can you please share more details on your use case?

**Comment by mathio** [comment]
After doing some testing it looks like preloaded forms do not sufficiently decrease the perceived loading time. We do not want to load unnecessary resources on host page if the embed modal might not be opened. 

When the modal is preloaded (left) it loads only slightly faster comapred to current implementation (right):
https://github.com/Typeform/embed/assets/1561771/767a3f45-e276-411e-9307-0e17856a990f

If you have a different use case, please feel free to share more details and reopen this issue.
