### ISSUE TITLE
Preview API for the individual response?

### ISSUE THREAD

**Issue by isaacdarcilla** [Typeform/embed#630]
Is there a way to embed a formatted preview of submissions/responses into an external page? Say an HTML page?

Just like Google Forms.

![image](https://github.com/Typeform/embed/assets/22732118/cf76101a-16c8-4f90-bbe9-61e2c045e4a4)

**Comment by mathio** [comment]
Hi @isaacdarcilla , this library is intended for embedding of the form itself.

If you want to embed responses, you can [create and share your responses report](https://www.typeform.com/help/a/create-and-share-your-responses-report-360029251552/). You can embed it in your page by putting it into an `<iframe>`.

Alternatively, if you want to display the responses in different format, you could fetch them via [Responses API](https://www.typeform.com/developers/responses/) and display them in your page.
