### ISSUE TITLE
Typescript error for partial-element-with-additional-attributes.d.ts

### ISSUE THREAD

**Issue by dmdinh22** [Typeform/embed#631]
![Screenshot 2023-12-27 093501](https://github.com/Typeform/embed/assets/7318190/204b0335-3bfe-4558-8124-d65015ca16ef)

I believe the error stems from the syntax `[key: data${string}]: string;` being invalid because TypeScript does not support template literals as keys in index signatures. There seems to be an issue with the TypeScript definitions provided by this library. Is there a workaround for this?

**Comment by mumpo** [comment]
Hi @dmdinh22 , thanks for reporting!

The issue you mention can be easily solved by upgrading the Typescript version you're using to >=4.4 (see [this documentation page](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-4.html#symbol-and-template-string-pattern-index-signatures), which describes when allowing template literals as index types was introduced to Typescript).

What's clear though is that the library is not clear about which versions of Typescript are supported, and we'll address that.
