### ISSUE TITLE
Modal close button needs accessible label

### ISSUE THREAD

**Issue by yvonnetangsu** [Typeform/embed#635]
Currently, the button to close a modal is an "x" that is announced as "times" by screen readers. This issue could be fixed by adding `aria-label="Close"` to the `<button>` element.

**Comment by mathio** [comment]
Hello @yvonnetangsu 

thank you for your suggestion. We have just released a new version with `aria-label`.

Enjoy 👍

**Comment by yvonnetangsu** [comment]
Thank you so much for the quick fix @mathio !
