### ISSUE TITLE
NextJS Typeform Embedding

### ISSUE THREAD

**Issue by SohamNagi** [Typeform/embed#649]
<img width="1017" alt="image" src="https://github.com/Typeform/embed/assets/104093080/aa9a9860-301e-4f86-b47c-c7365f353823">

NextJS integration doesn't seem to work whether I use a client side page or a server side page

**Comment by mathio** [comment]
Are you using AppRouter? I think we have tested with Pages router only.

**Comment by JacopoBonta** [comment]
Have you tried to wrap the Typeform component in a custom component with the `use client;` on top?

**Comment by mathio** [comment]
Hi @SohamNagi . I dont have much experience with the Next.js App Router, but it looks like you need to use [client component](https://nextjs.org/docs/app/building-your-application/rendering/client-components). 

In a recent PR https://github.com/Typeform/embed/pull/657 I am updating `demo-nextjs` to latest version of `next` and also including examples for the App Router. Hope this helps 🤞
