### ISSUE TITLE
Widget shows Typeform homepage when using React library

### ISSUE THREAD

**Issue by MaticConradi** [Typeform/embed#652]
The provided Nextjs code example displays the Typeform homepage in the embed instead of the provided form. I would like to note that I'm using Nextjs with the app directory, which has apparently not been tested. Manually importing the library as a script and doing it the old fashioned way also doesn't work; the form shows properly on initial load, but doesn't work when navigating from and then back to the (sub)page - though I assume this also has something to do with how Nextjs routing works. I have not done any digging beyond that.

**Comment by mathio** [comment]
@MaticConradi did you manage to resolve your issue? If not, please refer to my changes in a recent PR https://github.com/Typeform/embed/pull/657 I am updating `demo-nextjs` to latest version of `next` and also including examples for the App Router. I did not run into any issues. Hope this helps 🤞 

If not, feel free to reopen this issue with a reproducible example (a CodeSandbox or Github repo). Thanks.
