### ISSUE TITLE
Typescript: type issue with components ref

### ISSUE THREAD

**Issue by TommyBacco** [Typeform/embed#653]
It looks like there is some misalignment in the types when passing a `ref` making necessary to suppress the type error in order to proceed and use the components programmatically.

![image](https://github.com/Typeform/embed/assets/65162638/682d1d9a-186d-4b41-833b-983f5a64b639)

**Comment by Emkay2309** [comment]
Does Sidetab component excepts ref or not ??? 
Check that first , 
if it does try providing a type to ref as well 

interface SidetabProps extends React.HTMLAttributes<HTMLDivElement> {
    ref ?:  React.Ref<HTMLDivElement>;
}

ref?: React.Ref<HTMLDivElement>;

**Comment by FranRom** [comment]
The same is happening in the PopupButton and ref is in the documentation: 
https://github.com/Typeform/embed/tree/main/packages/embed-react#passing-a-custom-ref

The error I get is: 
`Type '{ children: string; ref: MutableRefObject<undefined>; id: string; hidden: { user: string; }; className: string; onSubmit: () => void; }' is not assignable to type 'IntrinsicAttributes & BaseOptions & ModalWindowOptions & UrlOptions & ActionableOptions & ... 5 more ... & ButtonComponentBaseProps'.
  Property 'ref' does not exist on type 'IntrinsicAttributes & BaseOptions & ModalWindowOptions & UrlOptions & ActionableOptions & ... 5 more ... & ButtonComponentBaseProps'`

**Comment by mathio** [comment]
Hello @TommyBacco @FranRom 

how do you define your `ref`? When i define it like this it works for me:

```js
const ref = useRef();
```

There are no TS errors on props or ref:
![Screenshot 2024-07-16 at 08 58 27](https://github.com/user-attachments/assets/623de07f-c8f1-4401-bf41-c2c6f1af2ece)

But it is true the ref is not typed properly, as it does not define the `open` method:
![Screenshot 2024-07-16 at 08 59 13](https://github.com/user-attachments/assets/431ee9c6-d681-41ce-a908-58af44433682)

I will look into this, if we can supply correct types on our side. In the meantime, as a workaround, I'd suggest typing as `any`:

```js
const ref = useRef<any>();
```

**Comment by mathio** [comment]
Actually you are right. I was building my test project [via vite](https://vitejs.dev/guide/features#transpile-only). When I build with `tsc --build`  the typescript did complain.

It proved to be quite challenging to type properly when we reuse React's `forwardRef`. I am renaming the prop instead to `embedRef` (since this is not actually a DOM element ref). Upcoming `@typeform/embed-react` version will introduce this breaking change.
