### ISSUE TITLE
Request ID should be sometimes undefined

### ISSUE THREAD

**Issue by jkjustjoshing** [Typeform/embed#662]
The `event` argument type passed to the `onSubmit` callback (and probably others, I didn't check) can be `undefined` when sandbox mode is enabled. However, the type definition says it's always a string.

Can be seen when using React

```jsx
<Widget 
  onSubmit={(event) => console.log(typeof event.responseId)}
  sandboxMode={true}
/>
```

`event.responseId` is `undefined` when sandbox mode is enabled, but the type definition is `string`, not `string | undefined`.

### The fix

Update [this line](https://github.com/Typeform/embed/blob/4c9aea13a526561886e4a718517ea462d07f0143/packages/embed/src/base/actionable-options.ts#L32C35-L32C49) to be

```typescript
  onSubmit?: (event: WithFormId & Partial<WithResponseId>) => void
```

However, that may indicate `responseId` is missing, not set to `undefined`, so you could also update `WithResponseId` to be `{ responseId: string | undefined }`, but I'm not sure where else that type is used and what the repercussion is.

**Comment by mathio** [comment]
Hello @jkjustjoshing 

Good catch! From the top of my head I dont see any issues with updating this to `{ responseId: string | undefined }`. I think we can update the type.
