### ISSUE TITLE
Can't export createWidget in Vite 5

### ISSUE THREAD

**Issue by skinofstars** [Typeform/embed#667]
Hi, I've got a Sveltekit 2 project using Vite 5. 

When I use `import { createWidget } from '@typeform/embed';` I can't build as I get the following error:

`"createWidget" is not exported by "node_modules/@typeform/embed/build/index.js"`

This has worked when I was using  Sveltekit 1, Vite 4.

**Comment by mathio** [comment]
I am sorry but I have no experience using Sveltekit and limited experience using Vite. Can you please provide a reproducible example for both cases - eg. a repo we can clone?

**Comment by skinofstars** [comment]
Hi, example repo is here

https://github.com/WhoTargetsMe/typeform-sveltekit-example

Previously I was only getting the error on build, but with this examplethe error is in both build and dev.

<img width="1127" alt="image" src="https://github.com/user-attachments/assets/ada5034a-3ec2-4a75-90fd-e765eeb058e7">

**Comment by mathio** [comment]
Hi @skinofstars 

Are you still experiencing an issue with this?

I played around with your example. It looks like importing the embed lib like this works:

```js
import * as pkg from '@typeform/embed';
```

My no experience with Svelte is limited, though. We did not test the lib with this framework.

Sorry for the delayed response.

**Comment by skinofstars** [comment]
Hi, yes I did fix this! 

My problem was `document.createElement("div")`. Once I bound to the element directly it worked. This is a working Typeform component in Svelte:

```svelte
<script lang="ts">
	import '@typeform/embed/build/css/widget.css';
	import { createWidget } from '@typeform/embed';
	import { onMount } from 'svelte';

	export let formId: string;
	export let options = {};

	let elem: HTMLElement;

	onMount(() => {
		try {
			createWidget(formId, {
				container: elem,
				...options
			});
		} catch (error) {
			console.error('Error creating Typeform widget', error);
		}
	});
</script>

<div bind:this={elem} />
```

**Comment by mathio** [comment]
Thats great to hear 🚀 Thanks for sharing!
