### ISSUE TITLE
[BUG] Window undefined error in next.js

### ISSUE THREAD

**Issue by conorshaw** [Typeform/embed#68]
**Describe the bug**
Trying to use library in next.js and getting window is undefined when using makeWidget within useEffect which is client side rendered only

**To Reproduce**
See basic example in repo:
https://github.com/conorshaw/typeform-next

**Expected behavior**
Shouldn't error out with window undefined when client side rendered

**Current behavior**
Throws window is undefined error

**Comment by landsman** [comment]
We have same problem.

**Comment by prilutskiy** [comment]
@conorshaw @landsman 
Hi, thanks for reporting this! Our team will start looking into this shortly.

P.S. Big thanks for the repro repo!

**Comment by linconkusunoki** [comment]
@prilutskiy it still with the error on the latest version

https://codesandbox.io/s/typeform-window-undefined-k113h?file=/pages/index.js

**Comment by seanislegend** [comment]
You can workaround this by creating a new component to load Typeform. You can then import this new component using [Next's dynamic imports](https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr). Just ensure you set `ssr` to false in the config as this is how to get around window not being defined during server render.

For example:
`const TypeForm = dynamic(() => import('./TypeForm'), {ssr: false});`

And in Typeform.js

```
import React, {useEffect, useRef} from 'react';
import * as typeformEmbed from '@typeform/embed';

const TypeForm = ({url}) => {
    const $typeform = useRef(null);

    useEffect(() => {
        if ($typeform.current) {
            typeformEmbed.makeWidget($typeform.current, url, {});
        }
    }, []);

    return (
        <div
            className="ReactTypeformEmbed"
            ref={$typeform}
            style={{
                position: 'absolute',
                top: 0,
                left: 0,
                width: '100%',
                height: '100%',
                overflow: 'hidden'
            }}
        />
    );
};

export default TypeForm;
```
