### ISSUE TITLE
[BUG] Missing logo

### ISSUE THREAD

**Issue by cesarvarela** [Typeform/embed#81]
**Describe the bug**
The logo is not showing our logo when using this component but shows when I go to the typeform url directly.

**To Reproduce**
Use this.

**Expected behavior**
Should show the logo I guess.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Chrome latest
 -  "@typeform/embed": "^0.25.4",

**Comment by picsoung** [comment]
Hey @cesarvarela 

Thank you for reporting this issue.
Could you share with ys the URL of the form?
And also give details on how you embedded it?

This will help us to reproduce it

Thank you

**Comment by mathio** [comment]
We are unable to reproduce the issue.
