### ISSUE TITLE
[BUG] Error: JSONP request to https://admin.typeform.com/app/embed/.....?jsoncallback=? failed

### ISSUE THREAD

**Issue by malimccalla** [Typeform/embed#83]
**Describe the bug**
Following the set up in the readme I'm receiving this error

```
Unhandled Runtime Error
Error: JSONP request to https://admin.typeform.com/app/embed/g4Hulgf4?jsoncallback=? failed

Call Stack
HTMLScriptElement.jsonpScript.onerror
node_modules/@typeform/embed/lib/api.js (8333:0)
```

The console also shows this error

```
admin.typeform.com/app/embed/olz2XlNv?jsoncallback=?&jsoncallback=jsonp_1602775661907_18757:1 Failed to load resource: the server responded with a status of 404 ()
54b82ca6.b03245ebd761ac836a5e.js:1 
```

**To Reproduce**
1. Go to https://test.thespie.com/digital/the-reunion-livestream-inplayer/2535
2. Open the console to see the errors

**Expected behavior**
No errors

**Current behavior**
The JSONP fetch error for  `https://admin.typeform.com/app/embed/g4Hulgf4?jsoncallback=?` and the 404 for `admin.typeform.com/app/embed/olz2XlNv?jsoncallback=?&jsoncallback=jsonp_1602775661907_18757`

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - latest

**Comment by mathio** [comment]
Can you please provide the JS code you use for embedding?

**Comment by malimccalla** [comment]
I managed to solve this by updating to the latest version. Thanks.

**Comment by fazi8808** [comment]
@mathio @malimccalla I still see that in my next.js project. Also, my version currently is the latest one.

![image](https://user-images.githubusercontent.com/26847943/100206747-8f0b1e80-2f28-11eb-9fac-dd36b20f740c.png)

![image](https://user-images.githubusercontent.com/26847943/100206899-c083ea00-2f28-11eb-98c5-5c614adc100a.png)

**Comment by JoeDenny** [comment]
@mathio I'm also getting the above error while using the latest version - any updates on this?

**Comment by lyzs90** [comment]
works for me after downgrading to v0.29.1

**Comment by travisldunn** [comment]
Can reopen this I am also running the latest version

**Comment by nikolovskipetar** [comment]
Did someone solves this?

**Comment by nikolovskipetar** [comment]
Did someone solve this?

**Comment by casesandberg** [comment]
I am getting this error with `react-typeform-embed@0.2.1`

```
<ReactTypeformEmbed
          url={url}
          onSubmit={handleSubmit}
/>
        ```

**Comment by mathio** [comment]
I am sorry but this is not a repository for `react-typeform-embed` lib which is not an official Typeform library. You will need to ask its author to upgrade to latest `@typeform/embed`.

At the moment we support only `@typeform/embed` (latest version is > 1). We are preparing an official react library soon.

**Comment by andirsun** [comment]
To solve this install the official ```@typeform/embed-react```
Then import like this
```
import {Widget} from '@typeform/embed-react'

...
<Widget
    id="pAHi9KR6"
    style={{height: '100vh', position: 'inherit'}}
  />

```
