### ISSUE TITLE
[BUG] onReady callback function is not called when form loads

### ISSUE THREAD

**Issue by tolulawson** [Typeform/embed#86]
[BUG] onReady callback function is not called when the Typeform loads

**Comment by prilutskiy** [comment]
@tolulawson thanks for reporting, we'll double-check this asap!

**Comment by tolulawson** [comment]
Hi Max,

Thank you so much for your help. I’ve found the reason for the error. I didn’t have @typeform/embed in my dependencies but instead had an unofficial React wrapper package.

I’ve fixed it now. Thanks
