### ISSUE TITLE
[FEATURE] Automatically resize iframe to avoid having scrollbars

### ISSUE THREAD

**Issue by schmidsi** [Typeform/embed#87]
**Is your feature request related to a problem? Please describe.**
On the site that I work on Typeform is embedded as a widget. And the users are confused by two scrollbars: One for the parent site and one for the Typeform.

**Describe the solution you'd like**
That the iframe automatically resizes according to the content.

**Describe alternatives you've considered**
I tried https://github.com/davidjbradshaw/iframe-resizer but it did not work.

**Additional context**
The idea would probably be to leverage `postMessage`

**Want to contribute?**
Maybe

**Comment by mathio** [comment]
Can you manually set iframe size to ensure your typeform always fits?

**Comment by schmidsi** [comment]
I already do this, but it's ugly: The size of the iFrame is dependent on the browser-width and for multi-step forms different steps have different heights. So to avoid scrollbars at all, I need to set the iFrame height to the highest which looks ugly.

**Comment by mathio** [comment]
To confirm - you would like to resize the iframe after respondent transitions between questions?

**Comment by schmidsi** [comment]
Exactly

**Comment by mathio** [comment]
Let me talk to the team and see if we can put such a feature on our roadmap. I will keep you updated.

**Comment by mathio** [comment]
This is problematic, because we calculate image size based on screen (iframe) size. We can not calculate question block size because it is based on the screen (iframe) size.

**Comment by schmidsi** [comment]
@mathio Please consider reopening this issue. It should be very easy: All you need to do is hoisting the difference content height to the window/iframe height so that the embedding website can adjust the iframe size.

It seems that the scrolling is happening on an element with a class like `block-scroller__Root` which contains the `block-scroller__Positioner` element which seems to be the one with the actual size of the form. I just need the height of this element to adjust the size of the iframe and the scrollbar would be gone.

**Comment by Sandstedt** [comment]
Would also wanna see this feature. Understand it could be problematic and require a big rewrite. But the UX for the visitor would be so much better.

**Use case:**
The landing screen is just a short question. The Typeform section on the page doesn't take so much space = easier to navigate or scroll past it if you don't wanna take the form. When interacting with the form, each question will adjust the height of the iframe needed to not cause an overflow. So it will look like the form is not embedded in an iframe but as a coherent part of the rest of the site / app.

This will allow the Typeform author/editor to add longer text/images without worrying about overflows.

A better architecture would be to skip the iframe entirely, and not use postion: absolute on all questions-wrappers (.BlockListItem__Wrapper), and instead let the content in the question dictate the height of the form container.
