### ISSUE TITLE
Redirection from iPad or iPhone to website is broken

### ISSUE THREAD

**Issue by isheraz** [Typeform/embed#89]
**Describe the bug**
The bug occurs when we try to redirect back to the website from the iframe. Something similar for payments has been explained [here](https://stackoverflow.com/questions/47691743/redirect-parent-page-from-iframe-in-ios/47695624#47695624). The solution is posted along with it, but there's no way to add params to `makeWidget` function

**To Reproduce**

Browser: Safari
User-Agent: iPad-mini/iphone/ipad
version: 13.1.3

Steps to reproduce the behaviour:
1. Go to 'https://demo.enotice.io/place/'
2. Click on 'state Kansas' > select any newspaper > click next > you should see a content prepared step click no
3. Select Name Change
4. Fill out the typeform 
5. See Loading Screen Stuck. 

**Expected behavior**
Repeat Same steps on Chrome, it should redirect back to the form without any issue. 

**Current behavior**
is stuck on loading screen on safari browser. 

**Smartphone :**
 - Device: iPad/iPad mini/iPhone
 - OS: iOS
 - Browser: safari
 - Version: 13.1.3

**Comment by mathio** [comment]
We will look into the issue next week. I will keep you updated.

**Comment by isheraz** [comment]
@mathio any update on the issue?

**Comment by mathio** [comment]
My colleague is looking into the issue right now.

Yesterday we had issues with replicating the issue on iPad (via Browserstack) as Cloudfare was returning Error 1010 - blocking access "based on browser signature" but it works now.

**Comment by isheraz** [comment]
> My colleague is looking into the issue right now.
> 
> Yesterday we had issues with replicating the issue on iPad (via Browserstack) as Cloudfare was returning Error 1010 - blocking access "based on browser signature" but it works now.

Awesome! thank you for the update. Another way to replicate this is by using the Safari browser and changing the user agent if that helps!

**Comment by mathio** [comment]
It looks like your form does not have the redirect set up (Create -> Settings -> Redirect on completion). 

A form with redirect works fine on an iPad: https://jsfiddle.net/mathio88/cmk32yzq/
