### ISSUE TITLE
[BUG] Typeform localStorage stays around for a recurring form

### ISSUE THREAD

**Issue by adilanchian** [Typeform/embed#95]
**Describe the bug**
We have a Typeform that will be used every week. When filling out the form, the answers for that form are populated with last weeks answers.

**To Reproduce**
1. Create a Typeform with the same ID
1. Submit the form successfully
1. Open up the form again

**Expected behavior**
Answers from the last submission should not be populated

**Current behavior**
Answers from the last submission are filled out completely on the new form

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Edge-Chromium / Chrome / Safari
 - Embed SDK Version: 0.25.6

**Additional context**
I am using the `makeWidget`.

Thanks!

**Comment by adilanchian** [comment]
Also - I saw `disableTracking` as a potential WidgetOption? Is this a thing? Thanks again!

**Comment by prilutskiy** [comment]
Hey @adilanchian, thanks for reporting this! We'll have a look at this.

**Comment by adilanchian** [comment]
Hey @prilutskiy much appreciated!

**Comment by mathio** [comment]
I was unable to replicate this. The form is populated with answers from past session only if the form was not submitted in that past session - this is correct and expected behavior.

@adilanchian can you please provide an example to replicate this issue?

**Comment by mathio** [comment]
I think a jsfiddle or something similar will be sufficient.

This is how I tested it: I created jsfiddle with a typeform here: https://jsfiddle.net/mathio88/cmk32yzq/ 

When the form is not submitted:
1. select one of the choices
2. reload page
3. the answer is preserved (correct)

When the form is submitted:
1. select one of the choices
2. submit the form
2. reload page
3. the answer is not preserved (correct)

**Comment by johnmcdowall** [comment]
I am also seeing this behaviour. Submitting a form, which works, then go around and trigger the typeform again and it's loading with the previous values.

**Comment by adilanchian** [comment]
Thanks for the insight here!

I haven't been able to give this a proper repro, but I believe it makes sense to repro this in a react project as it may point to our problem there!

**Comment by Thr44** [comment]
can you please confirm if this only occurs if we have a redirectAfterSubmitUrl ?

**Comment by Thr44** [comment]
hi, we just deployed https://jira.typeform.tf/browse/SB-4573 to resolve the issues with redirectAfterSubmitUrl.

**Comment by adilanchian** [comment]
Hey @Thr44 Thanks for the reply here!

So I actually haven't tried this out, but I don't use this flag at all in our react form. For some reason I didn't see this in the docs (though I might have missed it!)

I can try this out and report back if that's cool?

Thanks!

**Comment by johnmcdowall** [comment]
I've never heard of or used `redirectAfterSubmitUrl`. I'm just simply following the examples in the README in a React app.

**Comment by Thr44** [comment]
hey @adilanchian, @johnmcdowall if you still experience issues plz report back.

**Comment by adilanchian** [comment]
@Thr44 - Sorry for the late reply here! Quick question for you, would you be able to give me an example of how to use: `transferableUrlParameters` option? I have tried a few things and can't seem to find any docs on it... Would appreciate it!

@johnmcdowall - If you go to your TypeForm, in the web portal, you can toggle this option on: 

https://help.typeform.com/hc/en-us/articles/360029257112-Redirect-on-completion

In the library itself, there is an option to add a callback, `onSubmit` which is what I had been using to do my redirects, but I tried removing this event and then setup the redirect from the TypeForm itself and it looks like we are good to go! My fields are not repopulating. 

I guess the question now is - if you don't want a redirect does this still work?

**Comment by mathio** [comment]
# localStorage

I think the issue with localStorage was that the redirect happened too soon. 

As @adilanchian correctly pointed out, `redirectAfterSubmitUrl` is [set up via Typeform admin UI when you create form](https://help.typeform.com/hc/en-us/articles/360029257112-Redirect-on-completion).

# transferableUrlParameters

You can find examples in the demo directory:
* https://github.com/Typeform/embed/blob/8c47406672eb003586045cab4f8260855163d890/demo/popup-api.html#L154 (as array)
* https://github.com/Typeform/embed/blob/8c47406672eb003586045cab4f8260855163d890/demo/popup.html#L111 (as string with coma separated values)

Specified query params from your host page will be appended to form URL and available either as hidden field (if you set it up in your form) or in your form integration (eg. `utm_source` in Google Analytics integration).

**Comment by adilanchian** [comment]
@mathio 

Thanks for the quick reply here! Okay cool I did see this, so if I am understanding the `transferableUrlParameters` option:

I pass in an array of params I want to append to the form on submit. This may look something like this:

- I have hidden field `name`
- The value I want for name would be `Alec`
- In the `transferableUrlParameters` array I would pass in the string value: `name=Alec` 

Thanks again for the help on this!

**Comment by mathio** [comment]
No :) 

You have you own (host) page `www.example.com` with embedded typeform.

* add hidden field `name` in your form (via admin UI)
* setup `transferableUrlParameters: ['name']` (do not provide any value)
* visit `www.example.com?name=Alec`
* your hidden field `name` will populate with value `Alec` from the query param of the host page

**Comment by adilanchian** [comment]
Cheers!

**Comment by mathio** [comment]
Closing, localStorage issue is resolved. If you have other issues feel free to open a new issue.
