### ISSUE TITLE
[BUG] typeform embed script doesn't support RequireJS / define on frontend

### ISSUE THREAD

**Issue by janhorubala** [Typeform/embed#96]
I couldn't load typeform embed script on website that use RequireJS.

**Reproduce**
I added `<script src="https://embed.typeform.com/embed.js"></script>` via Google Tag Manager, but I still get `Uncaught ReferenceError: typeformEmbed is not defined`. The problem was with requireJS version 2.3.6 and line that imports typeform script
```
"object" == typeof exports && "object" == typeof module ? module.exports = t() : "function" == typeof define && define.amd ? define([], t) : "object" == typeof exports ? exports.typeformEmbed = t() : e.typeformEmbed = t()
```
RequireJS doesn't allow an empty array in `define([], t)`

**Dirty fix**
You can add typeform embed via GTM as below
```
<script>
  var tmpDefine = define;
  define = undefined;
  var el = document.createElement('script');
  el.src = 'https://embed.typeform.com/embed.js';
  el.onload = function() { define = tmpDefine };
  document.getElementsByTagName('head')[0].appendChild(el);
</script>
```

**Comment by prilutskiy** [comment]
@janhorubala hey, thanks for reporting! We'll have a look at this shortly.

**Comment by mathio** [comment]
Hi, I looked into the issue. If I understand this correctly GTM is loading the script asynchronously and it takes some time for the script to load. I dont know if there is any GTM event or callback for when it is done, but I confirmed this hypothesis via setTimeout :slightly_smiling_face: See https://jsfiddle.net/mathio88/6o158h7e/

**Comment by mathio** [comment]
If you have any issues with using our embed lib with RequireJS please refer to this example: 
https://glitch.com/edit/#!/embed-requirejs
